//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: service/followers/definition/followers.proto
// Note: requires additional types generated from: lib/protocol/attribute.proto
// Note: requires additional types generated from: lib/protocol/entity.proto
// Note: requires additional types generated from: lib/rpc/rpc.proto
namespace bnet.protocol.followers
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FollowedUser")]
  public partial class FollowedUser : global::ProtoBuf.IExtensible
  {
    public FollowedUser() {}
    
    private bnet.protocol.EntityId _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> _attribute = new global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute>();
    [global::ProtoBuf.ProtoMember(2, Name=@"attribute", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> attribute
    {
      get { return _attribute; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubscribeToFollowersRequest")]
  public partial class SubscribeToFollowersRequest : global::ProtoBuf.IExtensible
  {
    public SubscribeToFollowersRequest() {}
    

    private bnet.protocol.EntityId _agent_id = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"agent_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId agent_id
    {
      get { return _agent_id; }
      set { _agent_id = value; }
    }
    private ulong _object_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"object_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong object_id
    {
      get { return _object_id; }
      set { _object_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubscribeToFollowersResponse")]
  public partial class SubscribeToFollowersResponse : global::ProtoBuf.IExtensible
  {
    public SubscribeToFollowersResponse() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.followers.FollowedUser> _followed_users = new global::System.Collections.Generic.List<bnet.protocol.followers.FollowedUser>();
    [global::ProtoBuf.ProtoMember(2, Name=@"followed_users", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.followers.FollowedUser> followed_users
    {
      get { return _followed_users; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartFollowingRequest")]
  public partial class StartFollowingRequest : global::ProtoBuf.IExtensible
  {
    public StartFollowingRequest() {}
    

    private bnet.protocol.EntityId _agent_id = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"agent_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId agent_id
    {
      get { return _agent_id; }
      set { _agent_id = value; }
    }

    private bnet.protocol.EntityId _target_id = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"target_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId target_id
    {
      get { return _target_id; }
      set { _target_id = value; }
    }

    private string _follower_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"follower_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string follower_name
    {
      get { return _follower_name; }
      set { _follower_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartFollowingResponse")]
  public partial class StartFollowingResponse : global::ProtoBuf.IExtensible
  {
    public StartFollowingResponse() {}
    

    private bnet.protocol.followers.FollowedUser _followed_user = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"followed_user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.followers.FollowedUser followed_user
    {
      get { return _followed_user; }
      set { _followed_user = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StopFollowingRequest")]
  public partial class StopFollowingRequest : global::ProtoBuf.IExtensible
  {
    public StopFollowingRequest() {}
    

    private bnet.protocol.EntityId _agent_id = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"agent_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId agent_id
    {
      get { return _agent_id; }
      set { _agent_id = value; }
    }
    private bnet.protocol.EntityId _target_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"target_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId target_id
    {
      get { return _target_id; }
      set { _target_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StopFollowingResponse")]
  public partial class StopFollowingResponse : global::ProtoBuf.IExtensible
  {
    public StopFollowingResponse() {}
    

    private bnet.protocol.followers.FollowedUser _followed_user = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"followed_user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.followers.FollowedUser followed_user
    {
      get { return _followed_user; }
      set { _followed_user = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateFollowerStateRequest")]
  public partial class UpdateFollowerStateRequest : global::ProtoBuf.IExtensible
  {
    public UpdateFollowerStateRequest() {}
    

    private bnet.protocol.EntityId _agent_id = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"agent_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId agent_id
    {
      get { return _agent_id; }
      set { _agent_id = value; }
    }
    private bnet.protocol.EntityId _target_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"target_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId target_id
    {
      get { return _target_id; }
      set { _target_id = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> _attribute = new global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute>();
    [global::ProtoBuf.ProtoMember(3, Name=@"attribute", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> attribute
    {
      get { return _attribute; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateFollowerStateResponse")]
  public partial class UpdateFollowerStateResponse : global::ProtoBuf.IExtensible
  {
    public UpdateFollowerStateResponse() {}
    
    private bnet.protocol.EntityId _target_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"target_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId target_id
    {
      get { return _target_id; }
      set { _target_id = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> _attribute = new global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute>();
    [global::ProtoBuf.ProtoMember(3, Name=@"attribute", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> attribute
    {
      get { return _attribute; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FollowerNotification")]
  public partial class FollowerNotification : global::ProtoBuf.IExtensible
  {
    public FollowerNotification() {}
    
    private bnet.protocol.followers.FollowedUser _followed_user;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"followed_user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.followers.FollowedUser followed_user
    {
      get { return _followed_user; }
      set { _followed_user = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    public interface IFollowersService
    {
      bnet.protocol.followers.SubscribeToFollowersResponse SubscribeToFollowers(bnet.protocol.followers.SubscribeToFollowersRequest request);
    bnet.protocol.followers.StartFollowingResponse StartFollowing(bnet.protocol.followers.StartFollowingRequest request);
    bnet.protocol.followers.StopFollowingResponse StopFollowing(bnet.protocol.followers.StopFollowingRequest request);
    bnet.protocol.followers.UpdateFollowerStateResponse UpdateFollowerState(bnet.protocol.followers.UpdateFollowerStateRequest request);
    
    }
    
    
    public interface IFollowersNotify
    {
      bnet.protocol.NO_RESPONSE NotifyFollowerRemoved(bnet.protocol.followers.FollowerNotification request);
    
    }
    
    
}