//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: lib/rpc/connection.proto
// Note: requires additional types generated from: lib/rpc/rpc.proto
namespace bnet.protocol.connection
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConnectRequest")]
  public partial class ConnectRequest : global::ProtoBuf.IExtensible
  {
    public ConnectRequest() {}
    

    private bnet.protocol.ProcessId _client_id = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"client_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.ProcessId client_id
    {
      get { return _client_id; }
      set { _client_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConnectResponse")]
  public partial class ConnectResponse : global::ProtoBuf.IExtensible
  {
    public ConnectResponse() {}
    
    private bnet.protocol.ProcessId _server_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"server_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.ProcessId server_id
    {
      get { return _server_id; }
      set { _server_id = value; }
    }

    private bnet.protocol.ProcessId _client_id = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"client_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.ProcessId client_id
    {
      get { return _client_id; }
      set { _client_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BoundService")]
  public partial class BoundService : global::ProtoBuf.IExtensible
  {
    public BoundService() {}
    
    private uint _hash;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hash", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint hash
    {
      get { return _hash; }
      set { _hash = value; }
    }
    private uint _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BindRequest")]
  public partial class BindRequest : global::ProtoBuf.IExtensible
  {
    public BindRequest() {}
    
    private readonly global::System.Collections.Generic.List<uint> _imported_service_hash = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"imported_service_hash", DataFormat = global::ProtoBuf.DataFormat.FixedSize, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<uint> imported_service_hash
    {
      get { return _imported_service_hash; }
    }
  
    private readonly global::System.Collections.Generic.List<bnet.protocol.connection.BoundService> _exported_service = new global::System.Collections.Generic.List<bnet.protocol.connection.BoundService>();
    [global::ProtoBuf.ProtoMember(2, Name=@"exported_service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.connection.BoundService> exported_service
    {
      get { return _exported_service; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BindResponse")]
  public partial class BindResponse : global::ProtoBuf.IExtensible
  {
    public BindResponse() {}
    
    private readonly global::System.Collections.Generic.List<uint> _imported_service_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"imported_service_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<uint> imported_service_id
    {
      get { return _imported_service_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EchoRequest")]
  public partial class EchoRequest : global::ProtoBuf.IExtensible
  {
    public EchoRequest() {}
    

    private ulong _time = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong time
    {
      get { return _time; }
      set { _time = value; }
    }

    private bool _network_only = (bool)false;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"network_only", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool network_only
    {
      get { return _network_only; }
      set { _network_only = value; }
    }

    private byte[] _payload = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"payload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] payload
    {
      get { return _payload; }
      set { _payload = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EchoResponse")]
  public partial class EchoResponse : global::ProtoBuf.IExtensible
  {
    public EchoResponse() {}
    

    private ulong _time = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong time
    {
      get { return _time; }
      set { _time = value; }
    }

    private byte[] _payload = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"payload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] payload
    {
      get { return _payload; }
      set { _payload = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DisconnectRequest")]
  public partial class DisconnectRequest : global::ProtoBuf.IExtensible
  {
    public DisconnectRequest() {}
    
    private uint _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DisconnectNotification")]
  public partial class DisconnectNotification : global::ProtoBuf.IExtensible
  {
    public DisconnectNotification() {}
    
    private uint _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }

    private string _reason = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NullRequest")]
  public partial class NullRequest : global::ProtoBuf.IExtensible
  {
    public NullRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EncryptRequest")]
  public partial class EncryptRequest : global::ProtoBuf.IExtensible
  {
    public EncryptRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    public interface IConnectionService
    {
      bnet.protocol.connection.ConnectResponse Connect(bnet.protocol.connection.ConnectRequest request);
    bnet.protocol.connection.BindResponse Bind(bnet.protocol.connection.BindRequest request);
    bnet.protocol.connection.EchoResponse Echo(bnet.protocol.connection.EchoRequest request);
    bnet.protocol.NO_RESPONSE ForceDisconnect(bnet.protocol.connection.DisconnectNotification request);
    bnet.protocol.NO_RESPONSE Null(bnet.protocol.connection.NullRequest request);
    bnet.protocol.NoData Encrypt(bnet.protocol.connection.EncryptRequest request);
    bnet.protocol.NO_RESPONSE RequestDisconnect(bnet.protocol.connection.DisconnectRequest request);
    
    }
    
    
}