//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AttributeSerializer.proto
// Note: requires additional types generated from: GBHandle.proto
namespace D3.AttributeSerializer
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SavedAttribute")]
  public partial class SavedAttribute : global::ProtoBuf.IExtensible
  {
    public SavedAttribute() {}
    
    private int _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int key
    {
      get { return _key; }
      set { _key = value; }
    }
    private int _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SavedAttributes")]
  public partial class SavedAttributes : global::ProtoBuf.IExtensible
  {
    public SavedAttributes() {}
    
    private D3.GameBalance.Handle _gb_handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gb_handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public D3.GameBalance.Handle gb_handle
    {
      get { return _gb_handle; }
      set { _gb_handle = value; }
    }
    private readonly global::System.Collections.Generic.List<D3.AttributeSerializer.SavedAttribute> _attributes = new global::System.Collections.Generic.List<D3.AttributeSerializer.SavedAttribute>();
    [global::ProtoBuf.ProtoMember(2, Name=@"attributes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<D3.AttributeSerializer.SavedAttribute> attributes
    {
      get { return _attributes; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}