//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GameMessage.proto
// Note: requires additional types generated from: Hero.proto
// Note: requires additional types generated from: OnlineService.proto
// Note: requires additional types generated from: Settings.proto
// Note: requires additional types generated from: Account.proto
namespace D3.GameMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroDigestList")]
  public partial class HeroDigestList : global::ProtoBuf.IExtensible
  {
    public HeroDigestList() {}
    
    private D3.OnlineService.EntityId _account_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public D3.OnlineService.EntityId account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }
    private readonly global::System.Collections.Generic.List<D3.Hero.Digest> _digest_list = new global::System.Collections.Generic.List<D3.Hero.Digest>();
    [global::ProtoBuf.ProtoMember(2, Name=@"digest_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<D3.Hero.Digest> digest_list
    {
      get { return _digest_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientToonSettings")]
  public partial class ClientToonSettings : global::ProtoBuf.IExtensible
  {
    public ClientToonSettings() {}
    
    private D3.OnlineService.EntityId _toon_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"toon_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public D3.OnlineService.EntityId toon_id
    {
      get { return _toon_id; }
      set { _toon_id = value; }
    }
    private D3.Client.ToonSettings _client_toon_settings;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"client_toon_settings", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public D3.Client.ToonSettings client_toon_settings
    {
      get { return _client_toon_settings; }
      set { _client_toon_settings = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroDigestListRequest")]
  public partial class HeroDigestListRequest : global::ProtoBuf.IExtensible
  {
    public HeroDigestListRequest() {}
    
    private readonly global::System.Collections.Generic.List<D3.OnlineService.EntityId> _toon_id = new global::System.Collections.Generic.List<D3.OnlineService.EntityId>();
    [global::ProtoBuf.ProtoMember(1, Name=@"toon_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<D3.OnlineService.EntityId> toon_id
    {
      get { return _toon_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroDigestResponse")]
  public partial class HeroDigestResponse : global::ProtoBuf.IExtensible
  {
    public HeroDigestResponse() {}
    
    private D3.OnlineService.EntityId _toon_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"toon_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public D3.OnlineService.EntityId toon_id
    {
      get { return _toon_id; }
      set { _toon_id = value; }
    }
    private bool _success;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }

    private D3.Hero.Digest _hero_digest = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hero_digest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public D3.Hero.Digest hero_digest
    {
      get { return _hero_digest; }
      set { _hero_digest = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroDigestListResponse")]
  public partial class HeroDigestListResponse : global::ProtoBuf.IExtensible
  {
    public HeroDigestListResponse() {}
    
    private readonly global::System.Collections.Generic.List<D3.GameMessage.HeroDigestResponse> _digest_list = new global::System.Collections.Generic.List<D3.GameMessage.HeroDigestResponse>();
    [global::ProtoBuf.ProtoMember(1, Name=@"digest_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<D3.GameMessage.HeroDigestResponse> digest_list
    {
      get { return _digest_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerBanner")]
  public partial class PlayerBanner : global::ProtoBuf.IExtensible
  {
    public PlayerBanner() {}
    
    private uint _player_index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint player_index
    {
      get { return _player_index; }
      set { _player_index = value; }
    }
    private D3.Account.BannerConfiguration _banner;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"banner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public D3.Account.BannerConfiguration banner
    {
      get { return _banner; }
      set { _banner = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SaveBannerConfiguration")]
  public partial class SaveBannerConfiguration : global::ProtoBuf.IExtensible
  {
    public SaveBannerConfiguration() {}
    
    private D3.Account.BannerConfiguration _banner;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"banner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public D3.Account.BannerConfiguration banner
    {
      get { return _banner; }
      set { _banner = value; }
    }

    private uint _slot_index = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"slot_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint slot_index
    {
      get { return _slot_index; }
      set { _slot_index = value; }
    }

    private bool _make_active = (bool)true;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"make_active", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool make_active
    {
      get { return _make_active; }
      set { _make_active = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroDigestBanner")]
  public partial class HeroDigestBanner : global::ProtoBuf.IExtensible
  {
    public HeroDigestBanner() {}
    
    private D3.Hero.Digest _hero_digest;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hero_digest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public D3.Hero.Digest hero_digest
    {
      get { return _hero_digest; }
      set { _hero_digest = value; }
    }
    private D3.Account.BannerConfiguration _banner;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"banner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public D3.Account.BannerConfiguration banner
    {
      get { return _banner; }
      set { _banner = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameCurrentPlayers")]
  public partial class GameCurrentPlayers : global::ProtoBuf.IExtensible
  {
    public GameCurrentPlayers() {}
    
    private readonly global::System.Collections.Generic.List<D3.GameMessage.HeroDigestBanner> _players = new global::System.Collections.Generic.List<D3.GameMessage.HeroDigestBanner>();
    [global::ProtoBuf.ProtoMember(1, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<D3.GameMessage.HeroDigestBanner> players
    {
      get { return _players; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}