//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GBHandle.proto
namespace D3.GameBalance
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Handle")]
  public partial class Handle : global::ProtoBuf.IExtensible
  {
    public Handle() {}
    
    private int _game_balance_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"game_balance_type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int game_balance_type
    {
      get { return _game_balance_type; }
      set { _game_balance_type = value; }
    }
    private int _gbid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gbid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public int gbid
    {
      get { return _gbid; }
      set { _gbid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}