//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Hero.proto
// Note: requires additional types generated from: AttributeSerializer.proto
// Note: requires additional types generated from: Hireling.proto
// Note: requires additional types generated from: Items.proto
// Note: requires additional types generated from: OnlineService.proto
namespace D3.Hero
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VisualItem")]
  public partial class VisualItem : global::ProtoBuf.IExtensible
  {
    public VisualItem() {}
    

    private int _gbid = (int)-1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gbid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int gbid
    {
      get { return _gbid; }
      set { _gbid = value; }
    }

    private int _dye_type = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dye_type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int dye_type
    {
      get { return _dye_type; }
      set { _dye_type = value; }
    }

    private int _item_effect_type = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"item_effect_type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int item_effect_type
    {
      get { return _item_effect_type; }
      set { _item_effect_type = value; }
    }

    private int _effect_level = (int)-1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"effect_level", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int effect_level
    {
      get { return _effect_level; }
      set { _effect_level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VisualEquipment")]
  public partial class VisualEquipment : global::ProtoBuf.IExtensible
  {
    public VisualEquipment() {}
    
    private readonly global::System.Collections.Generic.List<D3.Hero.VisualItem> _visual_item = new global::System.Collections.Generic.List<D3.Hero.VisualItem>();
    [global::ProtoBuf.ProtoMember(1, Name=@"visual_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<D3.Hero.VisualItem> visual_item
    {
      get { return _visual_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QuestHistoryEntry")]
  public partial class QuestHistoryEntry : global::ProtoBuf.IExtensible
  {
    public QuestHistoryEntry() {}
    
    private int _sno_quest;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sno_quest", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public int sno_quest
    {
      get { return _sno_quest; }
      set { _sno_quest = value; }
    }
    private int _difficulty;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"difficulty", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int difficulty
    {
      get { return _difficulty; }
      set { _difficulty = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QuestRewardHistoryEntry")]
  public partial class QuestRewardHistoryEntry : global::ProtoBuf.IExtensible
  {
    public QuestRewardHistoryEntry() {}
    
    private int _sno_quest;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sno_quest", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public int sno_quest
    {
      get { return _sno_quest; }
      set { _sno_quest = value; }
    }
    private int _step_uid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"step_uid", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int step_uid
    {
      get { return _step_uid; }
      set { _step_uid = value; }
    }
    private int _difficulty;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"difficulty", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int difficulty
    {
      get { return _difficulty; }
      set { _difficulty = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Digest")]
  public partial class Digest : global::ProtoBuf.IExtensible
  {
    public Digest() {}
    
    private uint _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint version
    {
      get { return _version; }
      set { _version = value; }
    }
    private D3.OnlineService.EntityId _hero_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public D3.OnlineService.EntityId hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private string _hero_name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hero_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string hero_name
    {
      get { return _hero_name; }
      set { _hero_name = value; }
    }
    private int _gbid_class;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"gbid_class", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public int gbid_class
    {
      get { return _gbid_class; }
      set { _gbid_class = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _player_flags;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"player_flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint player_flags
    {
      get { return _player_flags; }
      set { _player_flags = value; }
    }
    private D3.Hero.VisualEquipment _visual_equipment;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"visual_equipment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public D3.Hero.VisualEquipment visual_equipment
    {
      get { return _visual_equipment; }
      set { _visual_equipment = value; }
    }
    private readonly global::System.Collections.Generic.List<D3.Hero.QuestHistoryEntry> _quest_history = new global::System.Collections.Generic.List<D3.Hero.QuestHistoryEntry>();
    [global::ProtoBuf.ProtoMember(8, Name=@"quest_history", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<D3.Hero.QuestHistoryEntry> quest_history
    {
      get { return _quest_history; }
    }
  
    private int _last_played_act;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"last_played_act", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int last_played_act
    {
      get { return _last_played_act; }
      set { _last_played_act = value; }
    }
    private int _highest_unlocked_act;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"highest_unlocked_act", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int highest_unlocked_act
    {
      get { return _highest_unlocked_act; }
      set { _highest_unlocked_act = value; }
    }
    private int _last_played_difficulty;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"last_played_difficulty", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int last_played_difficulty
    {
      get { return _last_played_difficulty; }
      set { _last_played_difficulty = value; }
    }
    private int _highest_unlocked_difficulty;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"highest_unlocked_difficulty", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int highest_unlocked_difficulty
    {
      get { return _highest_unlocked_difficulty; }
      set { _highest_unlocked_difficulty = value; }
    }
    private int _last_played_quest;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"last_played_quest", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public int last_played_quest
    {
      get { return _last_played_quest; }
      set { _last_played_quest = value; }
    }
    private int _last_played_quest_step;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"last_played_quest_step", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int last_played_quest_step
    {
      get { return _last_played_quest_step; }
      set { _last_played_quest_step = value; }
    }
    private uint _time_played;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"time_played", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint time_played
    {
      get { return _time_played; }
      set { _time_played = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HotbarButtonData")]
  public partial class HotbarButtonData : global::ProtoBuf.IExtensible
  {
    public HotbarButtonData() {}
    
    private int _sno_power;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sno_power", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public int sno_power
    {
      get { return _sno_power; }
      set { _sno_power = value; }
    }
    private int _gbid_item;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gbid_item", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public int gbid_item
    {
      get { return _gbid_item; }
      set { _gbid_item = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillKeyMapping")]
  public partial class SkillKeyMapping : global::ProtoBuf.IExtensible
  {
    public SkillKeyMapping() {}
    
    private int _sno_power;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sno_power", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public int sno_power
    {
      get { return _sno_power; }
      set { _sno_power = value; }
    }
    private int _id_hotkey;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id_hotkey", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int id_hotkey
    {
      get { return _id_hotkey; }
      set { _id_hotkey = value; }
    }
    private int _skill_button;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"skill_button", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int skill_button
    {
      get { return _skill_button; }
      set { _skill_button = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SavedQuest")]
  public partial class SavedQuest : global::ProtoBuf.IExtensible
  {
    public SavedQuest() {}
    
    private int _sno_quest;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sno_quest", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public int sno_quest
    {
      get { return _sno_quest; }
      set { _sno_quest = value; }
    }
    private int _difficulty;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"difficulty", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int difficulty
    {
      get { return _difficulty; }
      set { _difficulty = value; }
    }
    private int _current_step_uid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"current_step_uid", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int current_step_uid
    {
      get { return _current_step_uid; }
      set { _current_step_uid = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _objective_state = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"objective_state", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> objective_state
    {
      get { return _objective_state; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _failure_condition_state = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"failure_condition_state", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> failure_condition_state
    {
      get { return _failure_condition_state; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LearnedLore")]
  public partial class LearnedLore : global::ProtoBuf.IExtensible
  {
    public LearnedLore() {}
    
    private readonly global::System.Collections.Generic.List<int> _sno_lore_learned = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"sno_lore_learned", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<int> sno_lore_learned
    {
      get { return _sno_lore_learned; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SavedConversations")]
  public partial class SavedConversations : global::ProtoBuf.IExtensible
  {
    public SavedConversations() {}
    
    private byte[] _played_conversations_bitfield;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"played_conversations_bitfield", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] played_conversations_bitfield
    {
      get { return _played_conversations_bitfield; }
      set { _played_conversations_bitfield = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _sno_saved_conversations = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"sno_saved_conversations", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<int> sno_saved_conversations
    {
      get { return _sno_saved_conversations; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SavePointData_Proto")]
  public partial class SavePointData_Proto : global::ProtoBuf.IExtensible
  {
    public SavePointData_Proto() {}
    
    private int _sno_world;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sno_world", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public int sno_world
    {
      get { return _sno_world; }
      set { _sno_world = value; }
    }
    private int _savepoint_number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"savepoint_number", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int savepoint_number
    {
      get { return _savepoint_number; }
      set { _savepoint_number = value; }
    }
    private uint _creates_portal;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"creates_portal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint creates_portal
    {
      get { return _creates_portal; }
      set { _creates_portal = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SavedData")]
  public partial class SavedData : global::ProtoBuf.IExtensible
  {
    public SavedData() {}
    
    private readonly global::System.Collections.Generic.List<D3.Hero.HotbarButtonData> _hotbar_button_assignments = new global::System.Collections.Generic.List<D3.Hero.HotbarButtonData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"hotbar_button_assignments", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<D3.Hero.HotbarButtonData> hotbar_button_assignments
    {
      get { return _hotbar_button_assignments; }
    }
  
    private readonly global::System.Collections.Generic.List<D3.Hero.SkillKeyMapping> _skill_key_map = new global::System.Collections.Generic.List<D3.Hero.SkillKeyMapping>();
    [global::ProtoBuf.ProtoMember(2, Name=@"skill_key_map", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<D3.Hero.SkillKeyMapping> skill_key_map
    {
      get { return _skill_key_map; }
    }
  
    private uint _time_played;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"time_played", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint time_played
    {
      get { return _time_played; }
      set { _time_played = value; }
    }
    private uint _activated_waypoints;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"activated_waypoints", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint activated_waypoints
    {
      get { return _activated_waypoints; }
      set { _activated_waypoints = value; }
    }
    private D3.Hireling.SavedData _hireling_saved_data;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"hireling_saved_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public D3.Hireling.SavedData hireling_saved_data
    {
      get { return _hireling_saved_data; }
      set { _hireling_saved_data = value; }
    }
    private uint _last_level_time;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"last_level_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint last_level_time
    {
      get { return _last_level_time; }
      set { _last_level_time = value; }
    }
    private D3.Hero.LearnedLore _learned_lore;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"learned_lore", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public D3.Hero.LearnedLore learned_lore
    {
      get { return _learned_lore; }
      set { _learned_lore = value; }
    }
    private D3.Hero.SavedConversations _saved_conversations;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"saved_conversations", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public D3.Hero.SavedConversations saved_conversations
    {
      get { return _saved_conversations; }
      set { _saved_conversations = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _sno_active_skills = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"sno_active_skills", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<int> sno_active_skills
    {
      get { return _sno_active_skills; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _sno_traits = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"sno_traits", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<int> sno_traits
    {
      get { return _sno_traits; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _seen_tutorials = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(11, Name=@"seen_tutorials", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<int> seen_tutorials
    {
      get { return _seen_tutorials; }
    }
  
    private D3.Hero.SavePointData_Proto _save_point;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"save_point", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public D3.Hero.SavePointData_Proto save_point
    {
      get { return _save_point; }
      set { _save_point = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Timestamps")]
  public partial class Timestamps : global::ProtoBuf.IExtensible
  {
    public Timestamps() {}
    
    private long _create_time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"create_time", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public long create_time
    {
      get { return _create_time; }
      set { _create_time = value; }
    }

    private long _delete_time = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"delete_time", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long delete_time
    {
      get { return _delete_time; }
      set { _delete_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SavedDefinition")]
  public partial class SavedDefinition : global::ProtoBuf.IExtensible
  {
    public SavedDefinition() {}
    
    private uint _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint version
    {
      get { return _version; }
      set { _version = value; }
    }

    private D3.Hero.Digest _digest = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"digest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public D3.Hero.Digest digest
    {
      get { return _digest; }
      set { _digest = value; }
    }
    private D3.AttributeSerializer.SavedAttributes _saved_attributes;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"saved_attributes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public D3.AttributeSerializer.SavedAttributes saved_attributes
    {
      get { return _saved_attributes; }
      set { _saved_attributes = value; }
    }

    private D3.Hero.SavedData _saved_data = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"saved_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public D3.Hero.SavedData saved_data
    {
      get { return _saved_data; }
      set { _saved_data = value; }
    }
    private readonly global::System.Collections.Generic.List<D3.Hero.SavedQuest> _saved_quest = new global::System.Collections.Generic.List<D3.Hero.SavedQuest>();
    [global::ProtoBuf.ProtoMember(5, Name=@"saved_quest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<D3.Hero.SavedQuest> saved_quest
    {
      get { return _saved_quest; }
    }
  

    private D3.Items.ItemList _items = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public D3.Items.ItemList items
    {
      get { return _items; }
      set { _items = value; }
    }
    private readonly global::System.Collections.Generic.List<D3.Hero.QuestRewardHistoryEntry> _quest_reward_history = new global::System.Collections.Generic.List<D3.Hero.QuestRewardHistoryEntry>();
    [global::ProtoBuf.ProtoMember(7, Name=@"quest_reward_history", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<D3.Hero.QuestRewardHistoryEntry> quest_reward_history
    {
      get { return _quest_reward_history; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NameSequence")]
  public partial class NameSequence : global::ProtoBuf.IExtensible
  {
    public NameSequence() {}
    

    private long _sequence = (long)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)0)]
    public long sequence
    {
      get { return _sequence; }
      set { _sequence = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NameText")]
  public partial class NameText : global::ProtoBuf.IExtensible
  {
    public NameText() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Escrow")]
  public partial class Escrow : global::ProtoBuf.IExtensible
  {
    public Escrow() {}
    
    private uint _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint version
    {
      get { return _version; }
      set { _version = value; }
    }

    private D3.Items.Generator _generator = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"generator", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public D3.Items.Generator generator
    {
      get { return _generator; }
      set { _generator = value; }
    }

    private D3.Hero.SavedData _hero_data = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hero_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public D3.Hero.SavedData hero_data
    {
      get { return _hero_data; }
      set { _hero_data = value; }
    }

    private uint _state = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}