//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ItemCrafting.proto
namespace D3.ItemCrafting
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CrafterData")]
  public partial class CrafterData : global::ProtoBuf.IExtensible
  {
    public CrafterData() {}
    
    private readonly global::System.Collections.Generic.List<int> _recipes = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"recipes", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<int> recipes
    {
      get { return _recipes; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _available_enchants = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"available_enchants", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<int> available_enchants
    {
      get { return _available_enchants; }
    }
  
    private int _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private long _cooldown_end;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"cooldown_end", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public long cooldown_end
    {
      get { return _cooldown_end; }
      set { _cooldown_end = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CrafterSavedData")]
  public partial class CrafterSavedData : global::ProtoBuf.IExtensible
  {
    public CrafterSavedData() {}
    
    private readonly global::System.Collections.Generic.List<D3.ItemCrafting.CrafterData> _crafter_data = new global::System.Collections.Generic.List<D3.ItemCrafting.CrafterData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"crafter_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<D3.ItemCrafting.CrafterData> crafter_data
    {
      get { return _crafter_data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}