//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: OnlineService.proto
namespace D3.OnlineService
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EntityId")]
  public partial class EntityId : global::ProtoBuf.IExtensible
  {
    public EntityId() {}
    
    private ulong _id_high;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id_high", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id_high
    {
      get { return _id_high; }
      set { _id_high = value; }
    }
    private ulong _id_low;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id_low", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id_low
    {
      get { return _id_low; }
      set { _id_low = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameId")]
  public partial class GameId : global::ProtoBuf.IExtensible
  {
    public GameId() {}
    
    private ulong _factory;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"factory", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong factory
    {
      get { return _factory; }
      set { _factory = value; }
    }
    private ulong _id_high;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id_high", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id_high
    {
      get { return _id_high; }
      set { _id_high = value; }
    }
    private ulong _id_low;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"id_low", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id_low
    {
      get { return _id_low; }
      set { _id_low = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemId")]
  public partial class ItemId : global::ProtoBuf.IExtensible
  {
    public ItemId() {}
    
    private ulong _id_high;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id_high", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id_high
    {
      get { return _id_high; }
      set { _id_high = value; }
    }
    private ulong _id_low;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id_low", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id_low
    {
      get { return _id_low; }
      set { _id_low = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoopCreateParams")]
  public partial class CoopCreateParams : global::ProtoBuf.IExtensible
  {
    public CoopCreateParams() {}
    
    private int _difficulty_level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"difficulty_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int difficulty_level
    {
      get { return _difficulty_level; }
      set { _difficulty_level = value; }
    }
    private int _act;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"act", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int act
    {
      get { return _act; }
      set { _act = value; }
    }
    private int _sno_quest;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sno_quest", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public int sno_quest
    {
      get { return _sno_quest; }
      set { _sno_quest = value; }
    }
    private int _quest_step_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"quest_step_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int quest_step_id
    {
      get { return _quest_step_id; }
      set { _quest_step_id = value; }
    }

    private D3.OnlineService.EntityId _resume_from_save_hero_id = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"resume_from_save_hero_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public D3.OnlineService.EntityId resume_from_save_hero_id
    {
      get { return _resume_from_save_hero_id; }
      set { _resume_from_save_hero_id = value; }
    }
    private bool _open_to_friends;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"open_to_friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool open_to_friends
    {
      get { return _open_to_friends; }
      set { _open_to_friends = value; }
    }

    private string _open_to_friends_message = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"open_to_friends_message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string open_to_friends_message
    {
      get { return _open_to_friends_message; }
      set { _open_to_friends_message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PvPCreateParams")]
  public partial class PvPCreateParams : global::ProtoBuf.IExtensible
  {
    public PvPCreateParams() {}
    
    private int _sno_world;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sno_world", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public int sno_world
    {
      get { return _sno_world; }
      set { _sno_world = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameCreateParams")]
  public partial class GameCreateParams : global::ProtoBuf.IExtensible
  {
    public GameCreateParams() {}
    
    private int _game_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"game_type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int game_type
    {
      get { return _game_type; }
      set { _game_type = value; }
    }
    private uint _creation_flags;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"creation_flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint creation_flags
    {
      get { return _creation_flags; }
      set { _creation_flags = value; }
    }

    private D3.OnlineService.CoopCreateParams _coop = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"coop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public D3.OnlineService.CoopCreateParams coop
    {
      get { return _coop; }
      set { _coop = value; }
    }

    private D3.OnlineService.PvPCreateParams _pvp = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pvp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public D3.OnlineService.PvPCreateParams pvp
    {
      get { return _pvp; }
      set { _pvp = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private bool _is_private;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"is_private", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_private
    {
      get { return _is_private; }
      set { _is_private = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroCreateParams")]
  public partial class HeroCreateParams : global::ProtoBuf.IExtensible
  {
    public HeroCreateParams() {}
    
    private int _gbid_class;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gbid_class", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public int gbid_class
    {
      get { return _gbid_class; }
      set { _gbid_class = value; }
    }
    private bool _is_hardcore;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"is_hardcore", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_hardcore
    {
      get { return _is_hardcore; }
      set { _is_hardcore = value; }
    }
    private bool _is_female;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"is_female", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_female
    {
      get { return _is_female; }
      set { _is_female = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}