//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PartyMessage.proto
// Note: requires additional types generated from: OnlineService.proto
namespace D3.PartyMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ScreenStatus")]
  public partial class ScreenStatus : global::ProtoBuf.IExtensible
  {
    public ScreenStatus() {}
    
    private int _screen;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"screen", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int screen
    {
      get { return _screen; }
      set { _screen = value; }
    }
    private int _status;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SearchForPublicGameParams")]
  public partial class SearchForPublicGameParams : global::ProtoBuf.IExtensible
  {
    public SearchForPublicGameParams() {}
    

    private long _start_time = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"start_time", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long start_time
    {
      get { return _start_time; }
      set { _start_time = value; }
    }

    private uint _seconds_to_search = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"seconds_to_search", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint seconds_to_search
    {
      get { return _seconds_to_search; }
      set { _seconds_to_search = value; }
    }

    private D3.OnlineService.GameCreateParams _game_params = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"game_params", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public D3.OnlineService.GameCreateParams game_params
    {
      get { return _game_params; }
      set { _game_params = value; }
    }

    private int _remove_reason = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"remove_reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int remove_reason
    {
      get { return _remove_reason; }
      set { _remove_reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}