//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Settings.proto
namespace D3.Client
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ToonSettings")]
  public partial class ToonSettings : global::ProtoBuf.IExtensible
  {
    public ToonSettings() {}
    

    private uint _ui_flags = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ui_flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint ui_flags
    {
      get { return _ui_flags; }
      set { _ui_flags = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameAccountSettings")]
  public partial class GameAccountSettings : global::ProtoBuf.IExtensible
  {
    public GameAccountSettings() {}
    

    private int _use_last_hero = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"use_last_hero", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int use_last_hero
    {
      get { return _use_last_hero; }
      set { _use_last_hero = value; }
    }

    private int _show_offline_toast = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"show_offline_toast", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int show_offline_toast
    {
      get { return _show_offline_toast; }
      set { _show_offline_toast = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}