//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: service/presence/presence_types.proto
// Note: requires additional types generated from: lib/protocol/attribute.proto
// Note: requires additional types generated from: lib/protocol/entity.proto
// Note: requires additional types generated from: service/channel/channel_types.proto
namespace bnet.protocol.presence
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FieldKey")]
  public partial class FieldKey : global::ProtoBuf.IExtensible
  {
    public FieldKey() {}
    
    private uint _program;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"program", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint program
    {
      get { return _program; }
      set { _program = value; }
    }
    private uint _group;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint group
    {
      get { return _group; }
      set { _group = value; }
    }
    private uint _field;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"field", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint field
    {
      get { return _field; }
      set { _field = value; }
    }

    private ulong _index = (ulong)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)0)]
    public ulong index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Field")]
  public partial class Field : global::ProtoBuf.IExtensible
  {
    public Field() {}
    
    private bnet.protocol.presence.FieldKey _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.presence.FieldKey key
    {
      get { return _key; }
      set { _key = value; }
    }
    private bnet.protocol.attribute.Variant _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.attribute.Variant value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FieldOperation")]
  public partial class FieldOperation : global::ProtoBuf.IExtensible
  {
    public FieldOperation() {}
    
    private bnet.protocol.presence.Field _field;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"field", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.presence.Field field
    {
      get { return _field; }
      set { _field = value; }
    }

    private bnet.protocol.presence.FieldOperation.OperationType _operation = bnet.protocol.presence.FieldOperation.OperationType.SET;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"operation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(bnet.protocol.presence.FieldOperation.OperationType.SET)]
    public bnet.protocol.presence.FieldOperation.OperationType operation
    {
      get { return _operation; }
      set { _operation = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"OperationType")]
    public enum OperationType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SET", Value=0)]
      SET = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLEAR", Value=1)]
      CLEAR = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChannelState")]
  public partial class ChannelState : global::ProtoBuf.IExtensible
  {
    public ChannelState() {}
    

    private bnet.protocol.EntityId _entity_id = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"entity_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId entity_id
    {
      get { return _entity_id; }
      set { _entity_id = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.presence.FieldOperation> _field_operation = new global::System.Collections.Generic.List<bnet.protocol.presence.FieldOperation>();
    [global::ProtoBuf.ProtoMember(2, Name=@"field_operation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.presence.FieldOperation> field_operation
    {
      get { return _field_operation; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}