//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: service/search/search_types.proto
namespace bnet.protocol.search
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Statistic")]
  public partial class Statistic : global::ProtoBuf.IExtensible
  {
    public Statistic() {}
    

    private uint _id = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Filter")]
  public partial class Filter : global::ProtoBuf.IExtensible
  {
    public Filter() {}
    
    private bnet.protocol.search.Statistic _statistic;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"statistic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.search.Statistic statistic
    {
      get { return _statistic; }
      set { _statistic = value; }
    }
    private bnet.protocol.search.Filter.Comparand _comparand;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"comparand", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public bnet.protocol.search.Filter.Comparand comparand
    {
      get { return _comparand; }
      set { _comparand = value; }
    }

    private bnet.protocol.search.Filter.SortDirection _sort_direction = bnet.protocol.search.Filter.SortDirection.ASC;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sort_direction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(bnet.protocol.search.Filter.SortDirection.ASC)]
    public bnet.protocol.search.Filter.SortDirection sort_direction
    {
      get { return _sort_direction; }
      set { _sort_direction = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Comparand")]
    public enum Comparand
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUALS", Value=0)]
      EQUALS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LESS_THAN", Value=1)]
      LESS_THAN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LESS_THAN_OR_EQUALS", Value=2)]
      LESS_THAN_OR_EQUALS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GREATER_THAN", Value=3)]
      GREATER_THAN = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GREATER_THAN_OR_EQUALS", Value=4)]
      GREATER_THAN_OR_EQUALS = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SortDirection")]
    public enum SortDirection
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ASC", Value=0)]
      ASC = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DESC", Value=1)]
      DESC = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Object")]
  public partial class Object : global::ProtoBuf.IExtensible
  {
    public Object() {}
    
    private byte[] _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] id
    {
      get { return _id; }
      set { _id = value; }
    }

    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.search.Statistic> _statistics = new global::System.Collections.Generic.List<bnet.protocol.search.Statistic>();
    [global::ProtoBuf.ProtoMember(3, Name=@"statistics", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.search.Statistic> statistics
    {
      get { return _statistics; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}