//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: service/chat/definition/chat_types.proto
// Note: requires additional types generated from: service/channel/channel_types.proto
namespace bnet.protocol.chat
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChannelState")]
  public partial class ChannelState : global::ProtoBuf.IExtensible
  {
    public ChannelState() {}
    

    private string _identity = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"identity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string identity
    {
      get { return _identity; }
      set { _identity = value; }
    }

    private uint _program = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"program", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint program
    {
      get { return _program; }
      set { _program = value; }
    }

    private uint _locale = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"locale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint locale
    {
      get { return _locale; }
      set { _locale = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}