//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: service/channel_invitation/definition/channel_invitation.proto
// Note: requires additional types generated from: lib/protocol/entity.proto
// Note: requires additional types generated from: lib/protocol/invitation.proto
// Note: requires additional types generated from: lib/rpc/rpc.proto
// Note: requires additional types generated from: service/channel/definition/channel.proto
// Note: requires additional types generated from: service/channel_invitation/channel_invitation_types.proto
namespace bnet.protocol.channel_invitation
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AcceptInvitationRequest")]
  public partial class AcceptInvitationRequest : global::ProtoBuf.IExtensible
  {
    public AcceptInvitationRequest() {}
    

    private bnet.protocol.EntityId _agent_id = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"agent_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId agent_id
    {
      get { return _agent_id; }
      set { _agent_id = value; }
    }
    private ulong _invitation_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"invitation_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong invitation_id
    {
      get { return _invitation_id; }
      set { _invitation_id = value; }
    }
    private ulong _object_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"object_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong object_id
    {
      get { return _object_id; }
      set { _object_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AcceptInvitationResponse")]
  public partial class AcceptInvitationResponse : global::ProtoBuf.IExtensible
  {
    public AcceptInvitationResponse() {}
    
    private ulong _object_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"object_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong object_id
    {
      get { return _object_id; }
      set { _object_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubscribeRequest")]
  public partial class SubscribeRequest : global::ProtoBuf.IExtensible
  {
    public SubscribeRequest() {}
    

    private bnet.protocol.EntityId _agent_id = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"agent_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId agent_id
    {
      get { return _agent_id; }
      set { _agent_id = value; }
    }
    private ulong _object_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"object_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong object_id
    {
      get { return _object_id; }
      set { _object_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubscribeResponse")]
  public partial class SubscribeResponse : global::ProtoBuf.IExtensible
  {
    public SubscribeResponse() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.channel_invitation.InvitationCollection> _collection = new global::System.Collections.Generic.List<bnet.protocol.channel_invitation.InvitationCollection>();
    [global::ProtoBuf.ProtoMember(1, Name=@"collection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.channel_invitation.InvitationCollection> collection
    {
      get { return _collection; }
    }
  
    private readonly global::System.Collections.Generic.List<bnet.protocol.invitation.Invitation> _received_invitation = new global::System.Collections.Generic.List<bnet.protocol.invitation.Invitation>();
    [global::ProtoBuf.ProtoMember(2, Name=@"received_invitation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.invitation.Invitation> received_invitation
    {
      get { return _received_invitation; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnsubscribeRequest")]
  public partial class UnsubscribeRequest : global::ProtoBuf.IExtensible
  {
    public UnsubscribeRequest() {}
    

    private bnet.protocol.EntityId _agent_id = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"agent_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId agent_id
    {
      get { return _agent_id; }
      set { _agent_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SuggestInvitationRequest")]
  public partial class SuggestInvitationRequest : global::ProtoBuf.IExtensible
  {
    public SuggestInvitationRequest() {}
    

    private bnet.protocol.EntityId _agent_id = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"agent_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId agent_id
    {
      get { return _agent_id; }
      set { _agent_id = value; }
    }
    private bnet.protocol.EntityId _channel_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private bnet.protocol.EntityId _target_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"target_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId target_id
    {
      get { return _target_id; }
      set { _target_id = value; }
    }

    private bnet.protocol.EntityId _approval_id = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"approval_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId approval_id
    {
      get { return _approval_id; }
      set { _approval_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RevokeInvitationRequest")]
  public partial class RevokeInvitationRequest : global::ProtoBuf.IExtensible
  {
    public RevokeInvitationRequest() {}
    

    private bnet.protocol.EntityId _agent_id = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"agent_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId agent_id
    {
      get { return _agent_id; }
      set { _agent_id = value; }
    }

    private bnet.protocol.EntityId _target_id = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"target_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId target_id
    {
      get { return _target_id; }
      set { _target_id = value; }
    }
    private ulong _invitation_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"invitation_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong invitation_id
    {
      get { return _invitation_id; }
      set { _invitation_id = value; }
    }
    private bnet.protocol.EntityId _channel_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HasRoomForInvitationRequest")]
  public partial class HasRoomForInvitationRequest : global::ProtoBuf.IExtensible
  {
    public HasRoomForInvitationRequest() {}
    
    private uint _service_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"service_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint service_type
    {
      get { return _service_type; }
      set { _service_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InvitationAddedNotification")]
  public partial class InvitationAddedNotification : global::ProtoBuf.IExtensible
  {
    public InvitationAddedNotification() {}
    
    private bnet.protocol.invitation.Invitation _invitation;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"invitation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.invitation.Invitation invitation
    {
      get { return _invitation; }
      set { _invitation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InvitationRemovedNotification")]
  public partial class InvitationRemovedNotification : global::ProtoBuf.IExtensible
  {
    public InvitationRemovedNotification() {}
    
    private bnet.protocol.invitation.Invitation _invitation;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"invitation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.invitation.Invitation invitation
    {
      get { return _invitation; }
      set { _invitation = value; }
    }

    private uint _reason = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SuggestionAddedNotification")]
  public partial class SuggestionAddedNotification : global::ProtoBuf.IExtensible
  {
    public SuggestionAddedNotification() {}
    
    private bnet.protocol.invitation.Suggestion _suggestion;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"suggestion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.invitation.Suggestion suggestion
    {
      get { return _suggestion; }
      set { _suggestion = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    public interface IChannelInvitationService
    {
      bnet.protocol.channel_invitation.SubscribeResponse Subscribe(bnet.protocol.channel_invitation.SubscribeRequest request);
    bnet.protocol.NoData Unsubscribe(bnet.protocol.channel_invitation.UnsubscribeRequest request);
    bnet.protocol.invitation.SendInvitationResponse SendInvitation(bnet.protocol.invitation.SendInvitationRequest request);
    bnet.protocol.channel_invitation.AcceptInvitationResponse AcceptInvitation(bnet.protocol.channel_invitation.AcceptInvitationRequest request);
    bnet.protocol.NoData DeclineInvitation(bnet.protocol.invitation.GenericRequest request);
    bnet.protocol.NoData RevokeInvitation(bnet.protocol.channel_invitation.RevokeInvitationRequest request);
    bnet.protocol.NoData SuggestInvitation(bnet.protocol.channel_invitation.SuggestInvitationRequest request);
    
    }
    
    
    public interface IChannelInvitationNotify
    {
      bnet.protocol.NO_RESPONSE NotifyReceivedInvitationAdded(bnet.protocol.channel_invitation.InvitationAddedNotification request);
    bnet.protocol.NO_RESPONSE NotifyReceivedInvitationRemoved(bnet.protocol.channel_invitation.InvitationRemovedNotification request);
    bnet.protocol.NO_RESPONSE NotifyReceivedSuggestionAdded(bnet.protocol.channel_invitation.SuggestionAddedNotification request);
    bnet.protocol.NoData HasRoomForInvitation(bnet.protocol.channel_invitation.HasRoomForInvitationRequest request);
    
    }
    
    
}