//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: service/user_manager/user_manager.proto
// Note: requires additional types generated from: lib/protocol/attribute.proto
// Note: requires additional types generated from: lib/protocol/entity.proto
// Note: requires additional types generated from: lib/rpc/rpc.proto
namespace bnet.protocol.user_manager
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerReport")]
  public partial class PlayerReport : global::ProtoBuf.IExtensible
  {
    public PlayerReport() {}
    
    private bnet.protocol.user_manager.PlayerReport.UserComplaintCode _complaint_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"complaint_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public bnet.protocol.user_manager.PlayerReport.UserComplaintCode complaint_code
    {
      get { return _complaint_code; }
      set { _complaint_code = value; }
    }
    private string _complaint_note;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"complaint_note", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string complaint_note
    {
      get { return _complaint_note; }
      set { _complaint_note = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"UserComplaintCode")]
    public enum UserComplaintCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_COMPLAINT_SPAM", Value=0)]
      USER_COMPLAINT_SPAM = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_COMPLAINT_HARASSMENT", Value=1)]
      USER_COMPLAINT_HARASSMENT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_COMPLAINT_REAL_LIFE_THREAT", Value=2)]
      USER_COMPLAINT_REAL_LIFE_THREAT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_COMPLAINT_INAPPROPRIATE_NAME", Value=3)]
      USER_COMPLAINT_INAPPROPRIATE_NAME = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_COMPLAINT_HACKING", Value=4)]
      USER_COMPLAINT_HACKING = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_COMPLAINT_ANY", Value=5)]
      USER_COMPLAINT_ANY = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RecentPlayer")]
  public partial class RecentPlayer : global::ProtoBuf.IExtensible
  {
    public RecentPlayer() {}
    
    private bnet.protocol.EntityId _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId player
    {
      get { return _player; }
      set { _player = value; }
    }

    private ulong _timestamp_played = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"timestamp_played", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong timestamp_played
    {
      get { return _timestamp_played; }
      set { _timestamp_played = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> _attributes = new global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute>();
    [global::ProtoBuf.ProtoMember(3, Name=@"attributes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> attributes
    {
      get { return _attributes; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubscribeToUserManagerRequest")]
  public partial class SubscribeToUserManagerRequest : global::ProtoBuf.IExtensible
  {
    public SubscribeToUserManagerRequest() {}
    
    private ulong _object_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"object_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong object_id
    {
      get { return _object_id; }
      set { _object_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubscribeToUserManagerResponse")]
  public partial class SubscribeToUserManagerResponse : global::ProtoBuf.IExtensible
  {
    public SubscribeToUserManagerResponse() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.EntityId> _blocked_users = new global::System.Collections.Generic.List<bnet.protocol.EntityId>();
    [global::ProtoBuf.ProtoMember(1, Name=@"blocked_users", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.EntityId> blocked_users
    {
      get { return _blocked_users; }
    }
  
    private readonly global::System.Collections.Generic.List<bnet.protocol.user_manager.RecentPlayer> _recent_players = new global::System.Collections.Generic.List<bnet.protocol.user_manager.RecentPlayer>();
    [global::ProtoBuf.ProtoMember(2, Name=@"recent_players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.user_manager.RecentPlayer> recent_players
    {
      get { return _recent_players; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReportPlayerRequest")]
  public partial class ReportPlayerRequest : global::ProtoBuf.IExtensible
  {
    public ReportPlayerRequest() {}
    
    private bnet.protocol.EntityId _target_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"target_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId target_id
    {
      get { return _target_id; }
      set { _target_id = value; }
    }
    private bnet.protocol.user_manager.PlayerReport _report;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"report", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.user_manager.PlayerReport report
    {
      get { return _report; }
      set { _report = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReportPlayerResponse")]
  public partial class ReportPlayerResponse : global::ProtoBuf.IExtensible
  {
    public ReportPlayerResponse() {}
    

    private bnet.protocol.EntityId _reported_user = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reported_user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId reported_user
    {
      get { return _reported_user; }
      set { _reported_user = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CheckPlayerBlockRequest")]
  public partial class CheckPlayerBlockRequest : global::ProtoBuf.IExtensible
  {
    public CheckPlayerBlockRequest() {}
    
    private bnet.protocol.EntityId _target_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"target_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId target_id
    {
      get { return _target_id; }
      set { _target_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CheckPlayerBlockResponse")]
  public partial class CheckPlayerBlockResponse : global::ProtoBuf.IExtensible
  {
    public CheckPlayerBlockResponse() {}
    

    private bnet.protocol.EntityId _blocked_user = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"blocked_user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId blocked_user
    {
      get { return _blocked_user; }
      set { _blocked_user = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BlockPlayerRequest")]
  public partial class BlockPlayerRequest : global::ProtoBuf.IExtensible
  {
    public BlockPlayerRequest() {}
    
    private bnet.protocol.EntityId _target_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"target_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId target_id
    {
      get { return _target_id; }
      set { _target_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BlockPlayerResponse")]
  public partial class BlockPlayerResponse : global::ProtoBuf.IExtensible
  {
    public BlockPlayerResponse() {}
    

    private bnet.protocol.EntityId _blocked_user = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"blocked_user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId blocked_user
    {
      get { return _blocked_user; }
      set { _blocked_user = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemovePlayerBlockRequest")]
  public partial class RemovePlayerBlockRequest : global::ProtoBuf.IExtensible
  {
    public RemovePlayerBlockRequest() {}
    
    private bnet.protocol.EntityId _target_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"target_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId target_id
    {
      get { return _target_id; }
      set { _target_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemovePlayerBlockResponse")]
  public partial class RemovePlayerBlockResponse : global::ProtoBuf.IExtensible
  {
    public RemovePlayerBlockResponse() {}
    

    private bnet.protocol.EntityId _blocked_user = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"blocked_user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId blocked_user
    {
      get { return _blocked_user; }
      set { _blocked_user = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddRecentPlayersRequest")]
  public partial class AddRecentPlayersRequest : global::ProtoBuf.IExtensible
  {
    public AddRecentPlayersRequest() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.user_manager.RecentPlayer> _players = new global::System.Collections.Generic.List<bnet.protocol.user_manager.RecentPlayer>();
    [global::ProtoBuf.ProtoMember(1, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.user_manager.RecentPlayer> players
    {
      get { return _players; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddRecentPlayersResponse")]
  public partial class AddRecentPlayersResponse : global::ProtoBuf.IExtensible
  {
    public AddRecentPlayersResponse() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.user_manager.RecentPlayer> _players_added = new global::System.Collections.Generic.List<bnet.protocol.user_manager.RecentPlayer>();
    [global::ProtoBuf.ProtoMember(1, Name=@"players_added", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.user_manager.RecentPlayer> players_added
    {
      get { return _players_added; }
    }
  
    private readonly global::System.Collections.Generic.List<bnet.protocol.user_manager.RecentPlayer> _players_removed = new global::System.Collections.Generic.List<bnet.protocol.user_manager.RecentPlayer>();
    [global::ProtoBuf.ProtoMember(3, Name=@"players_removed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.user_manager.RecentPlayer> players_removed
    {
      get { return _players_removed; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveRecentPlayersRequest")]
  public partial class RemoveRecentPlayersRequest : global::ProtoBuf.IExtensible
  {
    public RemoveRecentPlayersRequest() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.user_manager.RecentPlayer> _players = new global::System.Collections.Generic.List<bnet.protocol.user_manager.RecentPlayer>();
    [global::ProtoBuf.ProtoMember(2, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.user_manager.RecentPlayer> players
    {
      get { return _players; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveRecentPlayersResponse")]
  public partial class RemoveRecentPlayersResponse : global::ProtoBuf.IExtensible
  {
    public RemoveRecentPlayersResponse() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.user_manager.RecentPlayer> _players_removed = new global::System.Collections.Generic.List<bnet.protocol.user_manager.RecentPlayer>();
    [global::ProtoBuf.ProtoMember(1, Name=@"players_removed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.user_manager.RecentPlayer> players_removed
    {
      get { return _players_removed; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BlockedPlayerNotification")]
  public partial class BlockedPlayerNotification : global::ProtoBuf.IExtensible
  {
    public BlockedPlayerNotification() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.EntityId> _players = new global::System.Collections.Generic.List<bnet.protocol.EntityId>();
    [global::ProtoBuf.ProtoMember(1, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.EntityId> players
    {
      get { return _players; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    public interface IUserManagerService
    {
      bnet.protocol.user_manager.SubscribeToUserManagerResponse SubscribeToUserManager(bnet.protocol.user_manager.SubscribeToUserManagerRequest request);
    bnet.protocol.user_manager.ReportPlayerResponse ReportPlayer(bnet.protocol.user_manager.ReportPlayerRequest request);
    bnet.protocol.user_manager.BlockPlayerResponse BlockPlayer(bnet.protocol.user_manager.BlockPlayerRequest request);
    bnet.protocol.user_manager.RemovePlayerBlockResponse RemovePlayerBlock(bnet.protocol.user_manager.RemovePlayerBlockRequest request);
    bnet.protocol.user_manager.AddRecentPlayersResponse AddRecentPlayers(bnet.protocol.user_manager.AddRecentPlayersRequest request);
    bnet.protocol.user_manager.RemoveRecentPlayersResponse RemoveRecentPlayers(bnet.protocol.user_manager.RemoveRecentPlayersRequest request);
    
    }
    
    
    public interface IUserManagerNotify
    {
      bnet.protocol.NO_RESPONSE NotifyPlayerBlocked(bnet.protocol.user_manager.BlockedPlayerNotification request);
    bnet.protocol.NO_RESPONSE NotifyPlayerBlockRemoved(bnet.protocol.user_manager.BlockedPlayerNotification request);
    
    }
    
    
}