//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: lib/config/process_config.proto
// Note: requires additional types generated from: lib/rpc/rpc.proto
namespace bnet.protocol.config
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Var")]
  public partial class Var : global::ProtoBuf.IExtensible
  {
    public Var() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Resource")]
  public partial class Resource : global::ProtoBuf.IExtensible
  {
    public Resource() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _url;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string url
    {
      get { return _url; }
      set { _url = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProgramResources")]
  public partial class ProgramResources : global::ProtoBuf.IExtensible
  {
    public ProgramResources() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.config.Resource> _program = new global::System.Collections.Generic.List<bnet.protocol.config.Resource>();
    [global::ProtoBuf.ProtoMember(1, Name=@"program", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.config.Resource> program
    {
      get { return _program; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerAddress")]
  public partial class ServerAddress : global::ProtoBuf.IExtensible
  {
    public ServerAddress() {}
    
    private bnet.protocol.Address _address;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.Address address
    {
      get { return _address; }
      set { _address = value; }
    }
    private string _process_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"process_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string process_name
    {
      get { return _process_name; }
      set { _process_name = value; }
    }

    private string _server_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"server_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string server_name
    {
      get { return _server_name; }
      set { _server_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerSet")]
  public partial class ServerSet : global::ProtoBuf.IExtensible
  {
    public ServerSet() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.config.ServerAddress> _server_address = new global::System.Collections.Generic.List<bnet.protocol.config.ServerAddress>();
    [global::ProtoBuf.ProtoMember(1, Name=@"server_address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.config.ServerAddress> server_address
    {
      get { return _server_address; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _exported_service = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"exported_service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> exported_service
    {
      get { return _exported_service; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _imported_service = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"imported_service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> imported_service
    {
      get { return _imported_service; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SupplementalService")]
  public partial class SupplementalService : global::ProtoBuf.IExtensible
  {
    public SupplementalService() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _port;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListenPoint")]
  public partial class ListenPoint : global::ProtoBuf.IExtensible
  {
    public ListenPoint() {}
    
    private uint _port;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }

    private string _address = @"0.0.0.0";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"0.0.0.0")]
    public string address
    {
      get { return _address; }
      set { _address = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.config.ServerSet> _accept = new global::System.Collections.Generic.List<bnet.protocol.config.ServerSet>();
    [global::ProtoBuf.ProtoMember(3, Name=@"accept", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.config.ServerSet> accept
    {
      get { return _accept; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServiceShard")]
  public partial class ServiceShard : global::ProtoBuf.IExtensible
  {
    public ServiceShard() {}
    
    private string _process_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"process_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string process_name
    {
      get { return _process_name; }
      set { _process_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServiceConfig")]
  public partial class ServiceConfig : global::ProtoBuf.IExtensible
  {
    public ServiceConfig() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _url;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string url
    {
      get { return _url; }
      set { _url = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.config.ServiceShard> _shard = new global::System.Collections.Generic.List<bnet.protocol.config.ServiceShard>();
    [global::ProtoBuf.ProtoMember(3, Name=@"shard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.config.ServiceShard> shard
    {
      get { return _shard; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RPCServerConfig")]
  public partial class RPCServerConfig : global::ProtoBuf.IExtensible
  {
    public RPCServerConfig() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private bnet.protocol.config.ListenPoint _listen = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"listen", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.config.ListenPoint listen
    {
      get { return _listen; }
      set { _listen = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.config.ServerSet> _connect = new global::System.Collections.Generic.List<bnet.protocol.config.ServerSet>();
    [global::ProtoBuf.ProtoMember(3, Name=@"connect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.config.ServerSet> connect
    {
      get { return _connect; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProcessConfig")]
  public partial class ProcessConfig : global::ProtoBuf.IExtensible
  {
    public ProcessConfig() {}
    
    private string _process_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"process_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string process_name
    {
      get { return _process_name; }
      set { _process_name = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.config.RPCServerConfig> _server = new global::System.Collections.Generic.List<bnet.protocol.config.RPCServerConfig>();
    [global::ProtoBuf.ProtoMember(2, Name=@"server", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.config.RPCServerConfig> server
    {
      get { return _server; }
    }
  
    private readonly global::System.Collections.Generic.List<bnet.protocol.config.Resource> _resource = new global::System.Collections.Generic.List<bnet.protocol.config.Resource>();
    [global::ProtoBuf.ProtoMember(3, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.config.Resource> resource
    {
      get { return _resource; }
    }
  
    private readonly global::System.Collections.Generic.List<bnet.protocol.config.ServiceConfig> _service = new global::System.Collections.Generic.List<bnet.protocol.config.ServiceConfig>();
    [global::ProtoBuf.ProtoMember(4, Name=@"service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.config.ServiceConfig> service
    {
      get { return _service; }
    }
  
    private readonly global::System.Collections.Generic.List<bnet.protocol.config.Var> _var = new global::System.Collections.Generic.List<bnet.protocol.config.Var>();
    [global::ProtoBuf.ProtoMember(5, Name=@"var", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.config.Var> var
    {
      get { return _var; }
    }
  
    private readonly global::System.Collections.Generic.List<bnet.protocol.config.SupplementalService> _supplemental_service = new global::System.Collections.Generic.List<bnet.protocol.config.SupplementalService>();
    [global::ProtoBuf.ProtoMember(6, Name=@"supplemental_service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.config.SupplementalService> supplemental_service
    {
      get { return _supplemental_service; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}