//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: service/storage/storage.proto
// Note: requires additional types generated from: lib/protocol/descriptor.proto
// Note: requires additional types generated from: lib/protocol/entity.proto
// Note: requires additional types generated from: lib/rpc/rpc.proto
namespace bnet.protocol.storage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TableId")]
  public partial class TableId : global::ProtoBuf.IExtensible
  {
    public TableId() {}
    
    private byte[] _hash;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hash", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] hash
    {
      get { return _hash; }
      set { _hash = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ColumnId")]
  public partial class ColumnId : global::ProtoBuf.IExtensible
  {
    public ColumnId() {}
    
    private byte[] _hash;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hash", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] hash
    {
      get { return _hash; }
      set { _hash = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RowId")]
  public partial class RowId : global::ProtoBuf.IExtensible
  {
    public RowId() {}
    
    private byte[] _hash;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hash", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] hash
    {
      get { return _hash; }
      set { _hash = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Privilege")]
  public partial class Privilege : global::ProtoBuf.IExtensible
  {
    public Privilege() {}
    

    private ulong _bits = (ulong)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bits", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((ulong)0)]
    public ulong bits
    {
      get { return _bits; }
      set { _bits = value; }
    }

    private uint _program = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"program", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint program
    {
      get { return _program; }
      set { _program = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Permission")]
    public enum Permission
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OWNER", Value=1)]
      OWNER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRIEND", Value=2)]
      FRIEND = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHER", Value=4)]
      OTHER = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME", Value=8)]
      GAME = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALL", Value=15)]
      ALL = 15
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ScanOperation")]
  public partial class ScanOperation : global::ProtoBuf.IExtensible
  {
    public ScanOperation() {}
    
    private bnet.protocol.storage.ScanOperation.Op _op;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"op", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public bnet.protocol.storage.ScanOperation.Op op
    {
      get { return _op; }
      set { _op = value; }
    }
    private bnet.protocol.Path _field;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"field", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.Path field
    {
      get { return _field; }
      set { _field = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Op")]
    public enum Op
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"IS_CLEAR", Value=1)]
      IS_CLEAR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_CLEAR", Value=2)]
      NOT_CLEAR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IS_EQUALS", Value=3)]
      IS_EQUALS = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_EQUALS", Value=4)]
      NOT_EQUALS = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IS_GREATER_THAN", Value=5)]
      IS_GREATER_THAN = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_GREATER_THAN", Value=6)]
      NOT_GREATER_THAN = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IS_LESS_THAN", Value=7)]
      IS_LESS_THAN = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_LESS_THAN", Value=8)]
      NOT_LESS_THAN = 8
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Command")]
  public partial class Command : global::ProtoBuf.IExtensible
  {
    public Command() {}
    
    private bnet.protocol.storage.Command.Op _op;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"op", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public bnet.protocol.storage.Command.Op op
    {
      get { return _op; }
      set { _op = value; }
    }

    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.Path> _fields = new global::System.Collections.Generic.List<bnet.protocol.Path>();
    [global::ProtoBuf.ProtoMember(3, Name=@"fields", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.Path> fields
    {
      get { return _fields; }
    }
  

    private ulong _min_version = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"min_version", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong min_version
    {
      get { return _min_version; }
      set { _min_version = value; }
    }

    private ulong _max_version = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"max_version", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong max_version
    {
      get { return _max_version; }
      set { _max_version = value; }
    }

    private bnet.protocol.storage.ScanOperation _scan = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"scan", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.storage.ScanOperation scan
    {
      get { return _scan; }
      set { _scan = value; }
    }

    private uint _limit = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint limit
    {
      get { return _limit; }
      set { _limit = value; }
    }

    private bnet.protocol.storage.Command.Cond _condition = bnet.protocol.storage.Command.Cond.COND_ALWAYS;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"condition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(bnet.protocol.storage.Command.Cond.COND_ALWAYS)]
    public bnet.protocol.storage.Command.Cond condition
    {
      get { return _condition; }
      set { _condition = value; }
    }

    private string _message = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Op")]
    public enum Op
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROW_DELETE", Value=1)]
      ROW_DELETE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROW_FETCH", Value=2)]
      ROW_FETCH = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COL_DELETE", Value=3)]
      COL_DELETE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COL_FETCH", Value=4)]
      COL_FETCH = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COL_WRITE", Value=5)]
      COL_WRITE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COL_MERGE", Value=6)]
      COL_MERGE = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FLD_CLEAR", Value=7)]
      FLD_CLEAR = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FLD_FETCH", Value=8)]
      FLD_FETCH = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FLD_WRITE", Value=9)]
      FLD_WRITE = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FLD_MERGE", Value=10)]
      FLD_MERGE = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FLD_INCR", Value=11)]
      FLD_INCR = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FLD_TEST", Value=12)]
      FLD_TEST = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FLD_SCAN", Value=13)]
      FLD_SCAN = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROW_TEST", Value=14)]
      ROW_TEST = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COL_TEST", Value=15)]
      COL_TEST = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FLD_SMAX", Value=16)]
      FLD_SMAX = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COL_COND", Value=17)]
      COL_COND = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FLD_COND", Value=18)]
      FLD_COND = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COND_POP", Value=19)]
      COND_POP = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_DEBUG", Value=20)]
      LOG_DEBUG = 20
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Cond")]
    public enum Cond
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"COND_ALWAYS", Value=0)]
      COND_ALWAYS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COND_NOT_EXISTS", Value=1)]
      COND_NOT_EXISTS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COND_NOT_EQUAL", Value=2)]
      COND_NOT_EQUAL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COND_LESS_THAN", Value=3)]
      COND_LESS_THAN = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COND_NOT_GREATER", Value=4)]
      COND_NOT_GREATER = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COND_EQUALS", Value=5)]
      COND_EQUALS = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COND_NOT_LESS", Value=6)]
      COND_NOT_LESS = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COND_GREATER_THAN", Value=7)]
      COND_GREATER_THAN = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COND_NEVER", Value=8)]
      COND_NEVER = 8
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Operation")]
  public partial class Operation : global::ProtoBuf.IExtensible
  {
    public Operation() {}
    
    private bnet.protocol.storage.TableId _table_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"table_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.storage.TableId table_id
    {
      get { return _table_id; }
      set { _table_id = value; }
    }

    private bnet.protocol.storage.ColumnId _column_id = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"column_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.storage.ColumnId column_id
    {
      get { return _column_id; }
      set { _column_id = value; }
    }

    private bnet.protocol.storage.RowId _row_id = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"row_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.storage.RowId row_id
    {
      get { return _row_id; }
      set { _row_id = value; }
    }

    private byte[] _row_key = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"row_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] row_key
    {
      get { return _row_key; }
      set { _row_key = value; }
    }

    private ulong _version = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong version
    {
      get { return _version; }
      set { _version = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.storage.Command> _rops = new global::System.Collections.Generic.List<bnet.protocol.storage.Command>();
    [global::ProtoBuf.ProtoMember(6, Name=@"rops", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.storage.Command> rops
    {
      get { return _rops; }
    }
  

    private ulong _mutate_version = default(ulong);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"mutate_version", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong mutate_version
    {
      get { return _mutate_version; }
      set { _mutate_version = value; }
    }

    private bnet.protocol.storage.Privilege _privilege = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"privilege", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.storage.Privilege privilege
    {
      get { return _privilege; }
      set { _privilege = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Cell")]
  public partial class Cell : global::ProtoBuf.IExtensible
  {
    public Cell() {}
    
    private bnet.protocol.storage.ColumnId _column_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"column_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.storage.ColumnId column_id
    {
      get { return _column_id; }
      set { _column_id = value; }
    }
    private bnet.protocol.storage.RowId _row_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"row_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.storage.RowId row_id
    {
      get { return _row_id; }
      set { _row_id = value; }
    }

    private byte[] _row_key = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"row_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] row_key
    {
      get { return _row_key; }
      set { _row_key = value; }
    }

    private ulong _version = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong version
    {
      get { return _version; }
      set { _version = value; }
    }

    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OperationResult")]
  public partial class OperationResult : global::ProtoBuf.IExtensible
  {
    public OperationResult() {}
    

    private uint _error_code = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private bnet.protocol.storage.TableId _table_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"table_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.storage.TableId table_id
    {
      get { return _table_id; }
      set { _table_id = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.storage.Cell> _data = new global::System.Collections.Generic.List<bnet.protocol.storage.Cell>();
    [global::ProtoBuf.ProtoMember(3, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.storage.Cell> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OpenTableRequest")]
  public partial class OpenTableRequest : global::ProtoBuf.IExtensible
  {
    public OpenTableRequest() {}
    

    private string _schema = @"DEFAULT";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"schema", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"DEFAULT")]
    public string schema
    {
      get { return _schema; }
      set { _schema = value; }
    }

    private bnet.protocol.storage.Privilege _privilege = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"privilege", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.storage.Privilege privilege
    {
      get { return _privilege; }
      set { _privilege = value; }
    }
    private bnet.protocol.storage.TableId _table_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"table_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.storage.TableId table_id
    {
      get { return _table_id; }
      set { _table_id = value; }
    }

    private bnet.protocol.EntityId _agent_id = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"agent_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId agent_id
    {
      get { return _agent_id; }
      set { _agent_id = value; }
    }

    private string _process_name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"process_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string process_name
    {
      get { return _process_name; }
      set { _process_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OpenTableResponse")]
  public partial class OpenTableResponse : global::ProtoBuf.IExtensible
  {
    public OpenTableResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OpenColumnRequest")]
  public partial class OpenColumnRequest : global::ProtoBuf.IExtensible
  {
    public OpenColumnRequest() {}
    

    private string _schema = @"DEFAULT";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"schema", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"DEFAULT")]
    public string schema
    {
      get { return _schema; }
      set { _schema = value; }
    }

    private bnet.protocol.storage.Privilege _privilege = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"privilege", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.storage.Privilege privilege
    {
      get { return _privilege; }
      set { _privilege = value; }
    }
    private bnet.protocol.storage.TableId _table_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"table_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.storage.TableId table_id
    {
      get { return _table_id; }
      set { _table_id = value; }
    }
    private bnet.protocol.storage.ColumnId _column_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"column_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.storage.ColumnId column_id
    {
      get { return _column_id; }
      set { _column_id = value; }
    }

    private string _proto_type = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"proto_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string proto_type
    {
      get { return _proto_type; }
      set { _proto_type = value; }
    }

    private bnet.protocol.EntityId _agent_id = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"agent_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId agent_id
    {
      get { return _agent_id; }
      set { _agent_id = value; }
    }

    private string _process_name = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"process_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string process_name
    {
      get { return _process_name; }
      set { _process_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OpenColumnResponse")]
  public partial class OpenColumnResponse : global::ProtoBuf.IExtensible
  {
    public OpenColumnResponse() {}
    

    private bool _server_field_ops = (bool)false;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"server_field_ops", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool server_field_ops
    {
      get { return _server_field_ops; }
      set { _server_field_ops = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExecuteRequest")]
  public partial class ExecuteRequest : global::ProtoBuf.IExtensible
  {
    public ExecuteRequest() {}
    

    private string _schema = @"DEFAULT";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"schema", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"DEFAULT")]
    public string schema
    {
      get { return _schema; }
      set { _schema = value; }
    }

    private bnet.protocol.storage.Privilege _privilege = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"privilege", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.storage.Privilege privilege
    {
      get { return _privilege; }
      set { _privilege = value; }
    }

    private bool _read_only = (bool)false;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"read_only", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool read_only
    {
      get { return _read_only; }
      set { _read_only = value; }
    }

    private bool _wants_row_key = (bool)false;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"wants_row_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool wants_row_key
    {
      get { return _wants_row_key; }
      set { _wants_row_key = value; }
    }

    private bool _wants_column_name = (bool)false;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"wants_column_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool wants_column_name
    {
      get { return _wants_column_name; }
      set { _wants_column_name = value; }
    }

    private uint _max_data_size = (uint)16777215;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"max_data_size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)16777215)]
    public uint max_data_size
    {
      get { return _max_data_size; }
      set { _max_data_size = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.storage.Operation> _operations = new global::System.Collections.Generic.List<bnet.protocol.storage.Operation>();
    [global::ProtoBuf.ProtoMember(7, Name=@"operations", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.storage.Operation> operations
    {
      get { return _operations; }
    }
  

    private uint _timeout = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"timeout", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint timeout
    {
      get { return _timeout; }
      set { _timeout = value; }
    }

    private bnet.protocol.EntityId _agent_id = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"agent_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId agent_id
    {
      get { return _agent_id; }
      set { _agent_id = value; }
    }

    private string _query_name = @"NoName";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"query_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"NoName")]
    public string query_name
    {
      get { return _query_name; }
      set { _query_name = value; }
    }

    private string _process_name = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"process_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string process_name
    {
      get { return _process_name; }
      set { _process_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExecuteResponse")]
  public partial class ExecuteResponse : global::ProtoBuf.IExtensible
  {
    public ExecuteResponse() {}
    

    private uint _error_code = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.storage.OperationResult> _results = new global::System.Collections.Generic.List<bnet.protocol.storage.OperationResult>();
    [global::ProtoBuf.ProtoMember(2, Name=@"results", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.storage.OperationResult> results
    {
      get { return _results; }
    }
  

    private string _error_message = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"error_message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string error_message
    {
      get { return _error_message; }
      set { _error_message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    public interface IStorageService
    {
      bnet.protocol.storage.ExecuteResponse Execute(bnet.protocol.storage.ExecuteRequest request);
    bnet.protocol.storage.OpenTableResponse OpenTable(bnet.protocol.storage.OpenTableRequest request);
    bnet.protocol.storage.OpenColumnResponse OpenColumn(bnet.protocol.storage.OpenColumnRequest request);
    
    }
    
    
}