//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: service/authentication/authentication.proto
// Note: requires additional types generated from: lib/rpc/rpc.proto
// Note: requires additional types generated from: lib/protocol/content_handle.proto
// Note: requires additional types generated from: lib/protocol/entity.proto
// Note: requires additional types generated from: lib/config/process_config.proto
namespace bnet.protocol.authentication
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ModuleLoadRequest")]
  public partial class ModuleLoadRequest : global::ProtoBuf.IExtensible
  {
    public ModuleLoadRequest() {}
    
    private bnet.protocol.ContentHandle _module_handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"module_handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.ContentHandle module_handle
    {
      get { return _module_handle; }
      set { _module_handle = value; }
    }

    private byte[] _message = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ModuleLoadResponse")]
  public partial class ModuleLoadResponse : global::ProtoBuf.IExtensible
  {
    public ModuleLoadResponse() {}
    

    private int _module_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"module_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int module_id
    {
      get { return _module_id; }
      set { _module_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ModuleMessageRequest")]
  public partial class ModuleMessageRequest : global::ProtoBuf.IExtensible
  {
    public ModuleMessageRequest() {}
    
    private int _module_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"module_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int module_id
    {
      get { return _module_id; }
      set { _module_id = value; }
    }

    private byte[] _message = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogonRequest")]
  public partial class LogonRequest : global::ProtoBuf.IExtensible
  {
    public LogonRequest() {}
    

    private string _program = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"program", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string program
    {
      get { return _program; }
      set { _program = value; }
    }

    private string _platform = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"platform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string platform
    {
      get { return _platform; }
      set { _platform = value; }
    }

    private string _locale = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"locale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string locale
    {
      get { return _locale; }
      set { _locale = value; }
    }

    private string _email = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"email", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string email
    {
      get { return _email; }
      set { _email = value; }
    }

    private ulong _listener_id = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"listener_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong listener_id
    {
      get { return _listener_id; }
      set { _listener_id = value; }
    }

    private string _version = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogonResponse")]
  public partial class LogonResponse : global::ProtoBuf.IExtensible
  {
    public LogonResponse() {}
    
    private bnet.protocol.EntityId _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId account
    {
      get { return _account; }
      set { _account = value; }
    }
    private bnet.protocol.EntityId _game_account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"game_account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId game_account
    {
      get { return _game_account; }
      set { _game_account = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AuthenticationConfig")]
  public partial class AuthenticationConfig : global::ProtoBuf.IExtensible
  {
    public AuthenticationConfig() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.config.Resource> _module = new global::System.Collections.Generic.List<bnet.protocol.config.Resource>();
    [global::ProtoBuf.ProtoMember(1, Name=@"module", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.config.Resource> module
    {
      get { return _module; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _allow_version = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"allow_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> allow_version
    {
      get { return _allow_version; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _deny_version = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"deny_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> deny_version
    {
      get { return _deny_version; }
    }
  
    private readonly global::System.Collections.Generic.List<bnet.protocol.config.Resource> _agreement = new global::System.Collections.Generic.List<bnet.protocol.config.Resource>();
    [global::ProtoBuf.ProtoMember(4, Name=@"agreement", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.config.Resource> agreement
    {
      get { return _agreement; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AuthModuleVariant")]
  public partial class AuthModuleVariant : global::ProtoBuf.IExtensible
  {
    public AuthModuleVariant() {}
    
    private string _platform;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"platform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string platform
    {
      get { return _platform; }
      set { _platform = value; }
    }
    private string _handle;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AuthModuleConfig")]
  public partial class AuthModuleConfig : global::ProtoBuf.IExtensible
  {
    public AuthModuleConfig() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.authentication.AuthModuleVariant> _variant = new global::System.Collections.Generic.List<bnet.protocol.authentication.AuthModuleVariant>();
    [global::ProtoBuf.ProtoMember(1, Name=@"variant", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.authentication.AuthModuleVariant> variant
    {
      get { return _variant; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AuthAgreementLocale")]
  public partial class AuthAgreementLocale : global::ProtoBuf.IExtensible
  {
    public AuthAgreementLocale() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _handle;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string handle
    {
      get { return _handle; }
      set { _handle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AuthAgreement")]
  public partial class AuthAgreement : global::ProtoBuf.IExtensible
  {
    public AuthAgreement() {}
    
    private string _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _program;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"program", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string program
    {
      get { return _program; }
      set { _program = value; }
    }
    private uint _scheme;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"scheme", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint scheme
    {
      get { return _scheme; }
      set { _scheme = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.authentication.AuthAgreementLocale> _locale = new global::System.Collections.Generic.List<bnet.protocol.authentication.AuthAgreementLocale>();
    [global::ProtoBuf.ProtoMember(4, Name=@"locale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.authentication.AuthAgreementLocale> locale
    {
      get { return _locale; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    public interface IAuthenticationClient
    {
      bnet.protocol.authentication.ModuleLoadResponse ModuleLoad(bnet.protocol.authentication.ModuleLoadRequest request);
    bnet.protocol.NoData ModuleMessage(bnet.protocol.authentication.ModuleMessageRequest request);
    
    }
    
    
    public interface IAuthenticationServer
    {
      bnet.protocol.authentication.LogonResponse Logon(bnet.protocol.authentication.LogonRequest request);
    bnet.protocol.NoData ModuleMessage(bnet.protocol.authentication.ModuleMessageRequest request);
    
    }
    
    
}