//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: service/channel_invitation/channel_invitation_types.proto
// Note: requires additional types generated from: lib/protocol/invitation.proto
// Note: requires additional types generated from: lib/protocol/entity.proto
// Note: requires additional types generated from: service/channel/channel_types.proto
namespace bnet.protocol.channel_invitation
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Invitation")]
  public partial class Invitation : global::ProtoBuf.IExtensible
  {
    public Invitation() {}
    
    private bnet.protocol.channel.ChannelDescription _channel_description;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel_description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.channel.ChannelDescription channel_description
    {
      get { return _channel_description; }
      set { _channel_description = value; }
    }

    private bool _reserved = (bool)false;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reserved", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool reserved
    {
      get { return _reserved; }
      set { _reserved = value; }
    }

    private bool _rejoin = (bool)false;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rejoin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool rejoin
    {
      get { return _rejoin; }
      set { _rejoin = value; }
    }

    private uint _service_type = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"service_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint service_type
    {
      get { return _service_type; }
      set { _service_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendInvitationRequest")]
  public partial class SendInvitationRequest : global::ProtoBuf.IExtensible
  {
    public SendInvitationRequest() {}
    

    private bnet.protocol.EntityId _channel_id = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }

    private bool _reserved = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reserved", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool reserved
    {
      get { return _reserved; }
      set { _reserved = value; }
    }

    private bool _rejoin = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rejoin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool rejoin
    {
      get { return _rejoin; }
      set { _rejoin = value; }
    }

    private uint _service_type = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"service_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint service_type
    {
      get { return _service_type; }
      set { _service_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InvitationCollection")]
  public partial class InvitationCollection : global::ProtoBuf.IExtensible
  {
    public InvitationCollection() {}
    

    private uint _service_type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"service_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint service_type
    {
      get { return _service_type; }
      set { _service_type = value; }
    }

    private uint _max_received_invitations = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"max_received_invitations", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint max_received_invitations
    {
      get { return _max_received_invitations; }
      set { _max_received_invitations = value; }
    }

    private ulong _object_id = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"object_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong object_id
    {
      get { return _object_id; }
      set { _object_id = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.invitation.Invitation> _received_invitation = new global::System.Collections.Generic.List<bnet.protocol.invitation.Invitation>();
    [global::ProtoBuf.ProtoMember(4, Name=@"received_invitation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.invitation.Invitation> received_invitation
    {
      get { return _received_invitation; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}