//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: service/game_master/game_factory.proto
// Note: requires additional types generated from: lib/protocol/attribute.proto
// Note: requires additional types generated from: lib/protocol/entity.proto
namespace bnet.protocol.game_master
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameProperties")]
  public partial class GameProperties : global::ProtoBuf.IExtensible
  {
    public GameProperties() {}
    

    private bnet.protocol.attribute.AttributeFilter _filter = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"filter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.attribute.AttributeFilter filter
    {
      get { return _filter; }
      set { _filter = value; }
    }

    private bool _create = (bool)false;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"create", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool create
    {
      get { return _create; }
      set { _create = value; }
    }

    private bool _open = (bool)true;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"open", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool open
    {
      get { return _open; }
      set { _open = value; }
    }

    private uint _program_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"program_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint program_id
    {
      get { return _program_id; }
      set { _program_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}