//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: service/game_master/game_master_types.proto
// Note: requires additional types generated from: lib/protocol/attribute.proto
// Note: requires additional types generated from: lib/protocol/entity.proto
namespace bnet.protocol.game_master
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Player")]
  public partial class Player : global::ProtoBuf.IExtensible
  {
    public Player() {}
    

    private bnet.protocol.game_master.Player.Type _type = bnet.protocol.game_master.Player.Type.TOON;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(bnet.protocol.game_master.Player.Type.TOON)]
    public bnet.protocol.game_master.Player.Type type
    {
      get { return _type; }
      set { _type = value; }
    }

    private bnet.protocol.EntityId _toon_id = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"toon_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId toon_id
    {
      get { return _toon_id; }
      set { _toon_id = value; }
    }

    private bnet.protocol.EntityId _game_account_id = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"game_account_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId game_account_id
    {
      get { return _game_account_id; }
      set { _game_account_id = value; }
    }

    private bnet.protocol.EntityId _bnet_account_id = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bnet_account_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId bnet_account_id
    {
      get { return _bnet_account_id; }
      set { _bnet_account_id = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> _attribute = new global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute>();
    [global::ProtoBuf.ProtoMember(5, Name=@"attribute", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> attribute
    {
      get { return _attribute; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TOON", Value=0)]
      TOON = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMPUTER", Value=1)]
      COMPUTER = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConnectInfo")]
  public partial class ConnectInfo : global::ProtoBuf.IExtensible
  {
    public ConnectInfo() {}
    
    private bnet.protocol.EntityId _toon_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"toon_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId toon_id
    {
      get { return _toon_id; }
      set { _toon_id = value; }
    }
    private string _host;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"host", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string host
    {
      get { return _host; }
      set { _host = value; }
    }
    private int _port;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int port
    {
      get { return _port; }
      set { _port = value; }
    }

    private byte[] _token = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] token
    {
      get { return _token; }
      set { _token = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> _attribute = new global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute>();
    [global::ProtoBuf.ProtoMember(5, Name=@"attribute", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> attribute
    {
      get { return _attribute; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameStatsBucket")]
  public partial class GameStatsBucket : global::ProtoBuf.IExtensible
  {
    public GameStatsBucket() {}
    

    private float _bucket_min = (float)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bucket_min", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float bucket_min
    {
      get { return _bucket_min; }
      set { _bucket_min = value; }
    }

    private float _bucket_max = (float)4.2949673e+009;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bucket_max", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)4.2949673e+009)]
    public float bucket_max
    {
      get { return _bucket_max; }
      set { _bucket_max = value; }
    }

    private uint _wait_milliseconds = (uint)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"wait_milliseconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint wait_milliseconds
    {
      get { return _wait_milliseconds; }
      set { _wait_milliseconds = value; }
    }

    private uint _games_per_hour = (uint)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"games_per_hour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint games_per_hour
    {
      get { return _games_per_hour; }
      set { _games_per_hour = value; }
    }

    private uint _active_games = (uint)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"active_games", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint active_games
    {
      get { return _active_games; }
      set { _active_games = value; }
    }

    private uint _active_players = (uint)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"active_players", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint active_players
    {
      get { return _active_players; }
      set { _active_players = value; }
    }

    private uint _forming_games = (uint)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"forming_games", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint forming_games
    {
      get { return _forming_games; }
      set { _forming_games = value; }
    }

    private uint _waiting_players = (uint)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"waiting_players", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint waiting_players
    {
      get { return _waiting_players; }
      set { _waiting_players = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameFactoryDescription")]
  public partial class GameFactoryDescription : global::ProtoBuf.IExtensible
  {
    public GameFactoryDescription() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> _attribute = new global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute>();
    [global::ProtoBuf.ProtoMember(3, Name=@"attribute", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> attribute
    {
      get { return _attribute; }
    }
  
    private readonly global::System.Collections.Generic.List<bnet.protocol.game_master.GameStatsBucket> _stats_bucket = new global::System.Collections.Generic.List<bnet.protocol.game_master.GameStatsBucket>();
    [global::ProtoBuf.ProtoMember(4, Name=@"stats_bucket", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.game_master.GameStatsBucket> stats_bucket
    {
      get { return _stats_bucket; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameHandle")]
  public partial class GameHandle : global::ProtoBuf.IExtensible
  {
    public GameHandle() {}
    
    private ulong _factory_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"factory_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong factory_id
    {
      get { return _factory_id; }
      set { _factory_id = value; }
    }
    private bnet.protocol.EntityId _game_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}