//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: service/game_master/game_master.proto
// Note: requires additional types generated from: service/game_master/game_factory.proto
// Note: requires additional types generated from: service/server_pool/server_pool.proto
// Note: requires additional types generated from: service/channel/channel_types.proto
// Note: requires additional types generated from: lib/protocol/attribute.proto
// Note: requires additional types generated from: lib/protocol/entity.proto
// Note: requires additional types generated from: lib/rpc/rpc.proto
// Note: requires additional types generated from: service/game_master/game_master_types.proto
namespace bnet.protocol.game_master
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinGameRequest")]
  public partial class JoinGameRequest : global::ProtoBuf.IExtensible
  {
    public JoinGameRequest() {}
    
    private bnet.protocol.game_master.GameHandle _game_handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"game_handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.game_master.GameHandle game_handle
    {
      get { return _game_handle; }
      set { _game_handle = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.game_master.Player> _player = new global::System.Collections.Generic.List<bnet.protocol.game_master.Player>();
    [global::ProtoBuf.ProtoMember(2, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.game_master.Player> player
    {
      get { return _player; }
    }
  

    private bnet.protocol.channel.JoinChannelRequest _channel_request = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"channel_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.channel.JoinChannelRequest channel_request
    {
      get { return _channel_request; }
      set { _channel_request = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinGameResponse")]
  public partial class JoinGameResponse : global::ProtoBuf.IExtensible
  {
    public JoinGameResponse() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.game_master.ConnectInfo> _connect_info = new global::System.Collections.Generic.List<bnet.protocol.game_master.ConnectInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"connect_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.game_master.ConnectInfo> connect_info
    {
      get { return _connect_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListFactoriesRequest")]
  public partial class ListFactoriesRequest : global::ProtoBuf.IExtensible
  {
    public ListFactoriesRequest() {}
    
    private bnet.protocol.attribute.AttributeFilter _filter;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"filter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.attribute.AttributeFilter filter
    {
      get { return _filter; }
      set { _filter = value; }
    }

    private uint _start_index = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"start_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint start_index
    {
      get { return _start_index; }
      set { _start_index = value; }
    }

    private uint _max_results = (uint)100;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"max_results", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)100)]
    public uint max_results
    {
      get { return _max_results; }
      set { _max_results = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListFactoriesResponse")]
  public partial class ListFactoriesResponse : global::ProtoBuf.IExtensible
  {
    public ListFactoriesResponse() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.game_master.GameFactoryDescription> _description = new global::System.Collections.Generic.List<bnet.protocol.game_master.GameFactoryDescription>();
    [global::ProtoBuf.ProtoMember(1, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.game_master.GameFactoryDescription> description
    {
      get { return _description; }
    }
  

    private uint _total_results = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"total_results", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint total_results
    {
      get { return _total_results; }
      set { _total_results = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FindGameRequest")]
  public partial class FindGameRequest : global::ProtoBuf.IExtensible
  {
    public FindGameRequest() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.game_master.Player> _player = new global::System.Collections.Generic.List<bnet.protocol.game_master.Player>();
    [global::ProtoBuf.ProtoMember(1, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.game_master.Player> player
    {
      get { return _player; }
    }
  

    private ulong _factory_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"factory_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong factory_id
    {
      get { return _factory_id; }
      set { _factory_id = value; }
    }

    private bnet.protocol.game_master.GameProperties _properties = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"properties", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.game_master.GameProperties properties
    {
      get { return _properties; }
      set { _properties = value; }
    }
    private ulong _object_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"object_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong object_id
    {
      get { return _object_id; }
      set { _object_id = value; }
    }

    private bnet.protocol.channel.CreateChannelRequest _channel_request = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"channel_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.channel.CreateChannelRequest channel_request
    {
      get { return _channel_request; }
      set { _channel_request = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FindGameResponse")]
  public partial class FindGameResponse : global::ProtoBuf.IExtensible
  {
    public FindGameResponse() {}
    

    private ulong _request_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"request_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong request_id
    {
      get { return _request_id; }
      set { _request_id = value; }
    }

    private ulong _factory_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"factory_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong factory_id
    {
      get { return _factory_id; }
      set { _factory_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CancelFindGameRequest")]
  public partial class CancelFindGameRequest : global::ProtoBuf.IExtensible
  {
    public CancelFindGameRequest() {}
    
    private ulong _factory_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"factory_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong factory_id
    {
      get { return _factory_id; }
      set { _factory_id = value; }
    }
    private ulong _request_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"request_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong request_id
    {
      get { return _request_id; }
      set { _request_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameEndedNotification")]
  public partial class GameEndedNotification : global::ProtoBuf.IExtensible
  {
    public GameEndedNotification() {}
    
    private bnet.protocol.game_master.GameHandle _game_handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"game_handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.game_master.GameHandle game_handle
    {
      get { return _game_handle; }
      set { _game_handle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerLeftNotification")]
  public partial class PlayerLeftNotification : global::ProtoBuf.IExtensible
  {
    public PlayerLeftNotification() {}
    
    private bnet.protocol.game_master.GameHandle _game_handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"game_handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.game_master.GameHandle game_handle
    {
      get { return _game_handle; }
      set { _game_handle = value; }
    }
    private bnet.protocol.EntityId _toon_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"toon_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId toon_id
    {
      get { return _toon_id; }
      set { _toon_id = value; }
    }

    private uint _reason = (uint)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterServerRequest")]
  public partial class RegisterServerRequest : global::ProtoBuf.IExtensible
  {
    public RegisterServerRequest() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> _attribute = new global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute>();
    [global::ProtoBuf.ProtoMember(1, Name=@"attribute", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> attribute
    {
      get { return _attribute; }
    }
  

    private bnet.protocol.server_pool.ServerState _state = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.server_pool.ServerState state
    {
      get { return _state; }
      set { _state = value; }
    }
    private uint _program_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"program_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint program_id
    {
      get { return _program_id; }
      set { _program_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnregisterServerRequest")]
  public partial class UnregisterServerRequest : global::ProtoBuf.IExtensible
  {
    public UnregisterServerRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterUtilitiesRequest")]
  public partial class RegisterUtilitiesRequest : global::ProtoBuf.IExtensible
  {
    public RegisterUtilitiesRequest() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> _attribute = new global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute>();
    [global::ProtoBuf.ProtoMember(1, Name=@"attribute", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> attribute
    {
      get { return _attribute; }
    }
  

    private bnet.protocol.server_pool.ServerState _state = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.server_pool.ServerState state
    {
      get { return _state; }
      set { _state = value; }
    }
    private uint _program_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"program_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint program_id
    {
      get { return _program_id; }
      set { _program_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnregisterUtilitiesRequest")]
  public partial class UnregisterUtilitiesRequest : global::ProtoBuf.IExtensible
  {
    public UnregisterUtilitiesRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubscribeRequest")]
  public partial class SubscribeRequest : global::ProtoBuf.IExtensible
  {
    public SubscribeRequest() {}
    
    private ulong _object_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"object_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong object_id
    {
      get { return _object_id; }
      set { _object_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubscribeResponse")]
  public partial class SubscribeResponse : global::ProtoBuf.IExtensible
  {
    public SubscribeResponse() {}
    

    private ulong _subscription_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"subscription_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong subscription_id
    {
      get { return _subscription_id; }
      set { _subscription_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnsubscribeRequest")]
  public partial class UnsubscribeRequest : global::ProtoBuf.IExtensible
  {
    public UnsubscribeRequest() {}
    
    private ulong _subscription_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"subscription_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong subscription_id
    {
      get { return _subscription_id; }
      set { _subscription_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeGameRequest")]
  public partial class ChangeGameRequest : global::ProtoBuf.IExtensible
  {
    public ChangeGameRequest() {}
    
    private bnet.protocol.game_master.GameHandle _game_handle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"game_handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.game_master.GameHandle game_handle
    {
      get { return _game_handle; }
      set { _game_handle = value; }
    }

    private bool _open = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"open", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool open
    {
      get { return _open; }
      set { _open = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> _attribute = new global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute>();
    [global::ProtoBuf.ProtoMember(3, Name=@"attribute", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> attribute
    {
      get { return _attribute; }
    }
  

    private bool _replace = (bool)false;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"replace", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool replace
    {
      get { return _replace; }
      set { _replace = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetFactoryInfoRequest")]
  public partial class GetFactoryInfoRequest : global::ProtoBuf.IExtensible
  {
    public GetFactoryInfoRequest() {}
    
    private ulong _factory_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"factory_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong factory_id
    {
      get { return _factory_id; }
      set { _factory_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetFactoryInfoResponse")]
  public partial class GetFactoryInfoResponse : global::ProtoBuf.IExtensible
  {
    public GetFactoryInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> _attribute = new global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute>();
    [global::ProtoBuf.ProtoMember(1, Name=@"attribute", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> attribute
    {
      get { return _attribute; }
    }
  
    private readonly global::System.Collections.Generic.List<bnet.protocol.game_master.GameStatsBucket> _stats_bucket = new global::System.Collections.Generic.List<bnet.protocol.game_master.GameStatsBucket>();
    [global::ProtoBuf.ProtoMember(2, Name=@"stats_bucket", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.game_master.GameStatsBucket> stats_bucket
    {
      get { return _stats_bucket; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetGameStatsRequest")]
  public partial class GetGameStatsRequest : global::ProtoBuf.IExtensible
  {
    public GetGameStatsRequest() {}
    
    private ulong _factory_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"factory_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong factory_id
    {
      get { return _factory_id; }
      set { _factory_id = value; }
    }
    private bnet.protocol.attribute.AttributeFilter _filter;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"filter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.attribute.AttributeFilter filter
    {
      get { return _filter; }
      set { _filter = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetGameStatsResponse")]
  public partial class GetGameStatsResponse : global::ProtoBuf.IExtensible
  {
    public GetGameStatsResponse() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.game_master.GameStatsBucket> _stats_bucket = new global::System.Collections.Generic.List<bnet.protocol.game_master.GameStatsBucket>();
    [global::ProtoBuf.ProtoMember(1, Name=@"stats_bucket", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.game_master.GameStatsBucket> stats_bucket
    {
      get { return _stats_bucket; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FactoryUpdateNotification")]
  public partial class FactoryUpdateNotification : global::ProtoBuf.IExtensible
  {
    public FactoryUpdateNotification() {}
    
    private bnet.protocol.game_master.FactoryUpdateNotification.Operation _op;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"op", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public bnet.protocol.game_master.FactoryUpdateNotification.Operation op
    {
      get { return _op; }
      set { _op = value; }
    }
    private bnet.protocol.game_master.GameFactoryDescription _description;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.game_master.GameFactoryDescription description
    {
      get { return _description; }
      set { _description = value; }
    }

    private uint _program_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"program_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint program_id
    {
      get { return _program_id; }
      set { _program_id = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Operation")]
    public enum Operation
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADD", Value=1)]
      ADD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REMOVE", Value=2)]
      REMOVE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHANGE", Value=3)]
      CHANGE = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameFoundNotification")]
  public partial class GameFoundNotification : global::ProtoBuf.IExtensible
  {
    public GameFoundNotification() {}
    
    private ulong _request_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"request_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong request_id
    {
      get { return _request_id; }
      set { _request_id = value; }
    }

    private uint _error_code = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }

    private bnet.protocol.game_master.GameHandle _game_handle = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"game_handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.game_master.GameHandle game_handle
    {
      get { return _game_handle; }
      set { _game_handle = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.game_master.ConnectInfo> _connect_info = new global::System.Collections.Generic.List<bnet.protocol.game_master.ConnectInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"connect_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.game_master.ConnectInfo> connect_info
    {
      get { return _connect_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    public interface IGameMaster
    {
      bnet.protocol.game_master.JoinGameResponse JoinGame(bnet.protocol.game_master.JoinGameRequest request);
    bnet.protocol.game_master.ListFactoriesResponse ListFactories(bnet.protocol.game_master.ListFactoriesRequest request);
    bnet.protocol.game_master.FindGameResponse FindGame(bnet.protocol.game_master.FindGameRequest request);
    bnet.protocol.NoData CancelFindGame(bnet.protocol.game_master.CancelFindGameRequest request);
    bnet.protocol.NO_RESPONSE GameEnded(bnet.protocol.game_master.GameEndedNotification request);
    bnet.protocol.NO_RESPONSE PlayerLeft(bnet.protocol.game_master.PlayerLeftNotification request);
    bnet.protocol.NoData RegisterServer(bnet.protocol.game_master.RegisterServerRequest request);
    bnet.protocol.NO_RESPONSE UnregisterServer(bnet.protocol.game_master.UnregisterServerRequest request);
    bnet.protocol.NoData RegisterUtilities(bnet.protocol.game_master.RegisterUtilitiesRequest request);
    bnet.protocol.NO_RESPONSE UnregisterUtilities(bnet.protocol.game_master.UnregisterUtilitiesRequest request);
    bnet.protocol.game_master.SubscribeResponse Subscribe(bnet.protocol.game_master.SubscribeRequest request);
    bnet.protocol.NO_RESPONSE Unsubscribe(bnet.protocol.game_master.UnsubscribeRequest request);
    bnet.protocol.NoData ChangeGame(bnet.protocol.game_master.ChangeGameRequest request);
    bnet.protocol.game_master.GetFactoryInfoResponse GetFactoryInfo(bnet.protocol.game_master.GetFactoryInfoRequest request);
    bnet.protocol.game_master.GetGameStatsResponse GetGameStats(bnet.protocol.game_master.GetGameStatsRequest request);
    
    }
    
    
    public interface IGameMasterSubscriber
    {
      bnet.protocol.NO_RESPONSE NotifyFactoryUpdate(bnet.protocol.game_master.FactoryUpdateNotification request);
    
    }
    
    
    public interface IGameFactorySubscriber
    {
      bnet.protocol.NO_RESPONSE NotifyGameFound(bnet.protocol.game_master.GameFoundNotification request);
    
    }
    
    
}