//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: service/channel/channel_types.proto
// Note: requires additional types generated from: lib/protocol/attribute.proto
// Note: requires additional types generated from: lib/protocol/entity.proto
// Note: requires additional types generated from: lib/protocol/invitation.proto
namespace bnet.protocol.channel
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Message")]
  public partial class Message : global::ProtoBuf.IExtensible
  {
    public Message() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> _attribute = new global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute>();
    [global::ProtoBuf.ProtoMember(1, Name=@"attribute", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> attribute
    {
      get { return _attribute; }
    }
  

    private uint _role = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"role", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role
    {
      get { return _role; }
      set { _role = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChannelDescription")]
  public partial class ChannelDescription : global::ProtoBuf.IExtensible
  {
    public ChannelDescription() {}
    
    private bnet.protocol.EntityId _channel_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }

    private uint _current_members = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"current_members", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint current_members
    {
      get { return _current_members; }
      set { _current_members = value; }
    }

    private bnet.protocol.channel.ChannelState _state = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.channel.ChannelState state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChannelInfo")]
  public partial class ChannelInfo : global::ProtoBuf.IExtensible
  {
    public ChannelInfo() {}
    
    private bnet.protocol.channel.ChannelDescription _description;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.channel.ChannelDescription description
    {
      get { return _description; }
      set { _description = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.channel.Member> _member = new global::System.Collections.Generic.List<bnet.protocol.channel.Member>();
    [global::ProtoBuf.ProtoMember(2, Name=@"member", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.channel.Member> member
    {
      get { return _member; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetChannelInfoRequest")]
  public partial class GetChannelInfoRequest : global::ProtoBuf.IExtensible
  {
    public GetChannelInfoRequest() {}
    

    private bnet.protocol.EntityId _agent_id = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"agent_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId agent_id
    {
      get { return _agent_id; }
      set { _agent_id = value; }
    }
    private bnet.protocol.EntityId _channel_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetChannelInfoResponse")]
  public partial class GetChannelInfoResponse : global::ProtoBuf.IExtensible
  {
    public GetChannelInfoResponse() {}
    

    private bnet.protocol.channel.ChannelInfo _channel_info = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"channel_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.channel.ChannelInfo channel_info
    {
      get { return _channel_info; }
      set { _channel_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetChannelIdRequest")]
  public partial class GetChannelIdRequest : global::ProtoBuf.IExtensible
  {
    public GetChannelIdRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetChannelIdResponse")]
  public partial class GetChannelIdResponse : global::ProtoBuf.IExtensible
  {
    public GetChannelIdResponse() {}
    

    private bnet.protocol.EntityId _channel_id = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateChannelRequest")]
  public partial class CreateChannelRequest : global::ProtoBuf.IExtensible
  {
    public CreateChannelRequest() {}
    

    private bnet.protocol.Identity _agent_identity = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"agent_identity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.Identity agent_identity
    {
      get { return _agent_identity; }
      set { _agent_identity = value; }
    }

    private bnet.protocol.channel.ChannelState _state = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.channel.ChannelState state
    {
      get { return _state; }
      set { _state = value; }
    }

    private bnet.protocol.EntityId _channel_id = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }

    private ulong _object_id = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"object_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong object_id
    {
      get { return _object_id; }
      set { _object_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateChannelResponse")]
  public partial class CreateChannelResponse : global::ProtoBuf.IExtensible
  {
    public CreateChannelResponse() {}
    
    private ulong _object_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"object_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong object_id
    {
      get { return _object_id; }
      set { _object_id = value; }
    }

    private bnet.protocol.EntityId _channel_id = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinChannelRequest")]
  public partial class JoinChannelRequest : global::ProtoBuf.IExtensible
  {
    public JoinChannelRequest() {}
    

    private bnet.protocol.Identity _agent_identity = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"agent_identity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.Identity agent_identity
    {
      get { return _agent_identity; }
      set { _agent_identity = value; }
    }
    private bnet.protocol.EntityId _channel_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private ulong _object_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"object_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong object_id
    {
      get { return _object_id; }
      set { _object_id = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.EntityId> _friend_account_id = new global::System.Collections.Generic.List<bnet.protocol.EntityId>();
    [global::ProtoBuf.ProtoMember(4, Name=@"friend_account_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.EntityId> friend_account_id
    {
      get { return _friend_account_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinChannelResponse")]
  public partial class JoinChannelResponse : global::ProtoBuf.IExtensible
  {
    public JoinChannelResponse() {}
    

    private ulong _object_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"object_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong object_id
    {
      get { return _object_id; }
      set { _object_id = value; }
    }

    private bool _require_friend_validation = (bool)false;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"require_friend_validation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool require_friend_validation
    {
      get { return _require_friend_validation; }
      set { _require_friend_validation = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.EntityId> _privileged_account = new global::System.Collections.Generic.List<bnet.protocol.EntityId>();
    [global::ProtoBuf.ProtoMember(3, Name=@"privileged_account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.EntityId> privileged_account
    {
      get { return _privileged_account; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FindChannelRequest")]
  public partial class FindChannelRequest : global::ProtoBuf.IExtensible
  {
    public FindChannelRequest() {}
    
    private bnet.protocol.attribute.AttributeFilter _filter;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"filter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.attribute.AttributeFilter filter
    {
      get { return _filter; }
      set { _filter = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FindChannelResponse")]
  public partial class FindChannelResponse : global::ProtoBuf.IExtensible
  {
    public FindChannelResponse() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.channel.ChannelDescription> _channel = new global::System.Collections.Generic.List<bnet.protocol.channel.ChannelDescription>();
    [global::ProtoBuf.ProtoMember(1, Name=@"channel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.channel.ChannelDescription> channel
    {
      get { return _channel; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChannelState")]
  public partial class ChannelState : global::ProtoBuf.IExtensible
  {
    public ChannelState() {}
    

    private uint _max_members = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"max_members", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint max_members
    {
      get { return _max_members; }
      set { _max_members = value; }
    }

    private uint _min_members = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"min_members", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint min_members
    {
      get { return _min_members; }
      set { _min_members = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> _attribute = new global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute>();
    [global::ProtoBuf.ProtoMember(3, Name=@"attribute", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> attribute
    {
      get { return _attribute; }
    }
  
    private readonly global::System.Collections.Generic.List<bnet.protocol.invitation.Invitation> _invitation = new global::System.Collections.Generic.List<bnet.protocol.invitation.Invitation>();
    [global::ProtoBuf.ProtoMember(4, Name=@"invitation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.invitation.Invitation> invitation
    {
      get { return _invitation; }
    }
  

    private uint _max_invitations = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"max_invitations", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint max_invitations
    {
      get { return _max_invitations; }
      set { _max_invitations = value; }
    }

    private uint _reason = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint reason
    {
      get { return _reason; }
      set { _reason = value; }
    }

    private bnet.protocol.channel.ChannelState.PrivacyLevel _privacy_level = bnet.protocol.channel.ChannelState.PrivacyLevel.PRIVACY_LEVEL_OPEN;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"privacy_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(bnet.protocol.channel.ChannelState.PrivacyLevel.PRIVACY_LEVEL_OPEN)]
    public bnet.protocol.channel.ChannelState.PrivacyLevel privacy_level
    {
      get { return _privacy_level; }
      set { _privacy_level = value; }
    }

    private bool _public = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"public", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool @public
    {
      get { return _public; }
      set { _public = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _delegate_name = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"delegate_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string delegate_name
    {
      get { return _delegate_name; }
      set { _delegate_name = value; }
    }

    private string _channel_type = @"default";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"channel_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"default")]
    public string channel_type
    {
      get { return _channel_type; }
      set { _channel_type = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"PrivacyLevel")]
    public enum PrivacyLevel
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRIVACY_LEVEL_OPEN", Value=1)]
      PRIVACY_LEVEL_OPEN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRIVACY_LEVEL_OPEN_INVITATION_AND_FRIEND", Value=2)]
      PRIVACY_LEVEL_OPEN_INVITATION_AND_FRIEND = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRIVACY_LEVEL_OPEN_INVITATION", Value=3)]
      PRIVACY_LEVEL_OPEN_INVITATION = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRIVACY_LEVEL_CLOSED", Value=4)]
      PRIVACY_LEVEL_CLOSED = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MemberState")]
  public partial class MemberState : global::ProtoBuf.IExtensible
  {
    public MemberState() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> _attribute = new global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute>();
    [global::ProtoBuf.ProtoMember(1, Name=@"attribute", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> attribute
    {
      get { return _attribute; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _role = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"role", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> role
    {
      get { return _role; }
    }
  

    private ulong _privileges = (ulong)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"privileges", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)0)]
    public ulong privileges
    {
      get { return _privileges; }
      set { _privileges = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Member")]
  public partial class Member : global::ProtoBuf.IExtensible
  {
    public Member() {}
    
    private bnet.protocol.Identity _identity;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"identity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.Identity identity
    {
      get { return _identity; }
      set { _identity = value; }
    }
    private bnet.protocol.channel.MemberState _state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.channel.MemberState state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}