//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: lib/protocol/attribute.proto
namespace bnet.protocol.attribute
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Variant")]
  public partial class Variant : global::ProtoBuf.IExtensible
  {
    public Variant() {}
    

    private bool _bool_value = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bool_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bool_value
    {
      get { return _bool_value; }
      set { _bool_value = value; }
    }

    private long _int_value = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"int_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long int_value
    {
      get { return _int_value; }
      set { _int_value = value; }
    }

    private double _float_value = default(double);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"float_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double float_value
    {
      get { return _float_value; }
      set { _float_value = value; }
    }

    private string _string_value = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"string_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string string_value
    {
      get { return _string_value; }
      set { _string_value = value; }
    }

    private byte[] _blob_value = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"blob_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] blob_value
    {
      get { return _blob_value; }
      set { _blob_value = value; }
    }

    private byte[] _message_value = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"message_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] message_value
    {
      get { return _message_value; }
      set { _message_value = value; }
    }

    private string _fourcc_value = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"fourcc_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fourcc_value
    {
      get { return _fourcc_value; }
      set { _fourcc_value = value; }
    }

    private ulong _uint_value = default(ulong);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"uint_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uint_value
    {
      get { return _uint_value; }
      set { _uint_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Attribute")]
  public partial class Attribute : global::ProtoBuf.IExtensible
  {
    public Attribute() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private bnet.protocol.attribute.Variant _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.attribute.Variant value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AttributeFilter")]
  public partial class AttributeFilter : global::ProtoBuf.IExtensible
  {
    public AttributeFilter() {}
    
    private bnet.protocol.attribute.AttributeFilter.Operation _op;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"op", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public bnet.protocol.attribute.AttributeFilter.Operation op
    {
      get { return _op; }
      set { _op = value; }
    }
    private readonly global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> _attribute = new global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute>();
    [global::ProtoBuf.ProtoMember(2, Name=@"attribute", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.attribute.Attribute> attribute
    {
      get { return _attribute; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Operation")]
    public enum Operation
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MATCH_NONE", Value=0)]
      MATCH_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MATCH_ANY", Value=1)]
      MATCH_ANY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MATCH_ALL", Value=2)]
      MATCH_ALL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MATCH_ALL_MOST_SPECIFIC", Value=3)]
      MATCH_ALL_MOST_SPECIFIC = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}