//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: lib/protocol/content_handle.proto
namespace bnet.protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ContentHandle")]
  public partial class ContentHandle : global::ProtoBuf.IExtensible
  {
    public ContentHandle() {}
    
    private uint _region;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"region", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint region
    {
      get { return _region; }
      set { _region = value; }
    }
    private uint _usage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"usage", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint usage
    {
      get { return _usage; }
      set { _usage = value; }
    }
    private byte[] _hash;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hash", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] hash
    {
      get { return _hash; }
      set { _hash = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}