//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: lib/protocol/entity.proto
namespace bnet.protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EntityId")]
  public partial class EntityId : global::ProtoBuf.IExtensible
  {
    public EntityId() {}
    
    private ulong _high;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"high", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong high
    {
      get { return _high; }
      set { _high = value; }
    }
    private ulong _low;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"low", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong low
    {
      get { return _low; }
      set { _low = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Identity")]
  public partial class Identity : global::ProtoBuf.IExtensible
  {
    public Identity() {}
    

    private bnet.protocol.EntityId _account_id = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"account_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private bnet.protocol.EntityId _game_account_id = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"game_account_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId game_account_id
    {
      get { return _game_account_id; }
      set { _game_account_id = value; }
    }

    private bnet.protocol.EntityId _toon_id = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"toon_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId toon_id
    {
      get { return _toon_id; }
      set { _toon_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}