//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: lib/protocol/exchange.proto
namespace bnet.protocol.exchange
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PartitionId")]
  public partial class PartitionId : global::ProtoBuf.IExtensible
  {
    public PartitionId() {}
    
    private ulong _high;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"high", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong high
    {
      get { return _high; }
      set { _high = value; }
    }
    private ulong _low;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"low", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong low
    {
      get { return _low; }
      set { _low = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BlobFrom")]
  public partial class BlobFrom : global::ProtoBuf.IExtensible
  {
    public BlobFrom() {}
    
    private uint _source;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"source", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint source
    {
      get { return _source; }
      set { _source = value; }
    }
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }

    private byte[] _extra_data = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"extra_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] extra_data
    {
      get { return _extra_data; }
      set { _extra_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BlobOfType")]
  public partial class BlobOfType : global::ProtoBuf.IExtensible
  {
    public BlobOfType() {}
    
    private string _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }

    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }

    private byte[] _extra_data = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"extra_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] extra_data
    {
      get { return _extra_data; }
      set { _extra_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BlobFromOfType")]
  public partial class BlobFromOfType : global::ProtoBuf.IExtensible
  {
    public BlobFromOfType() {}
    
    private uint _source;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"source", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint source
    {
      get { return _source; }
      set { _source = value; }
    }
    private string _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}