//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: lib/protocol/exchange_object_provider.proto
// Note: requires additional types generated from: lib/protocol/entity.proto
// Note: requires additional types generated from: lib/protocol/exchange.proto
namespace bnet.protocol.exchange_object_provider
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReportAuthorizeRequest")]
  public partial class ReportAuthorizeRequest : global::ProtoBuf.IExtensible
  {
    public ReportAuthorizeRequest() {}
    
    private bnet.protocol.exchange.PartitionId _partition_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"partition_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.exchange.PartitionId partition_id
    {
      get { return _partition_id; }
      set { _partition_id = value; }
    }
    private bnet.protocol.exchange.PartitionId _token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.exchange.PartitionId token
    {
      get { return _token; }
      set { _token = value; }
    }
    private ulong _result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong result
    {
      get { return _result; }
      set { _result = value; }
    }

    private bnet.protocol.exchange.BlobFromOfType _auth_handle = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"auth_handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.exchange.BlobFromOfType auth_handle
    {
      get { return _auth_handle; }
      set { _auth_handle = value; }
    }

    private bool _defer_delivery = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"defer_delivery", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool defer_delivery
    {
      get { return _defer_delivery; }
      set { _defer_delivery = value; }
    }
    private bnet.protocol.EntityId _bnet_account_id;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"bnet_account_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId bnet_account_id
    {
      get { return _bnet_account_id; }
      set { _bnet_account_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReportSettleRequest")]
  public partial class ReportSettleRequest : global::ProtoBuf.IExtensible
  {
    public ReportSettleRequest() {}
    
    private bnet.protocol.exchange.PartitionId _partition_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"partition_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.exchange.PartitionId partition_id
    {
      get { return _partition_id; }
      set { _partition_id = value; }
    }
    private bnet.protocol.exchange.PartitionId _token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.exchange.PartitionId token
    {
      get { return _token; }
      set { _token = value; }
    }
    private ulong _result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReportCancelRequest")]
  public partial class ReportCancelRequest : global::ProtoBuf.IExtensible
  {
    public ReportCancelRequest() {}
    
    private bnet.protocol.exchange.PartitionId _partition_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"partition_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.exchange.PartitionId partition_id
    {
      get { return _partition_id; }
      set { _partition_id = value; }
    }
    private bnet.protocol.exchange.PartitionId _token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.exchange.PartitionId token
    {
      get { return _token; }
      set { _token = value; }
    }
    private ulong _result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetPaymentMethodsRequest")]
  public partial class GetPaymentMethodsRequest : global::ProtoBuf.IExtensible
  {
    public GetPaymentMethodsRequest() {}
    

    private bnet.protocol.EntityId _bnet_account = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bnet_account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId bnet_account
    {
      get { return _bnet_account; }
      set { _bnet_account = value; }
    }

    private bnet.protocol.EntityId _game_account = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"game_account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId game_account
    {
      get { return _game_account; }
      set { _game_account = value; }
    }

    private bnet.protocol.EntityId _toon = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"toon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId toon
    {
      get { return _toon; }
      set { _toon = value; }
    }
    private string _currency;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"currency", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string currency
    {
      get { return _currency; }
      set { _currency = value; }
    }
    private uint _cash_in_out_mask;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"cash_in_out_mask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cash_in_out_mask
    {
      get { return _cash_in_out_mask; }
      set { _cash_in_out_mask = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PaymentMethod")]
  public partial class PaymentMethod : global::ProtoBuf.IExtensible
  {
    public PaymentMethod() {}
    
    private bnet.protocol.exchange.BlobFrom _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.exchange.BlobFrom account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _description;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }

    private ulong _amount = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetPaymentMethodsResponse")]
  public partial class GetPaymentMethodsResponse : global::ProtoBuf.IExtensible
  {
    public GetPaymentMethodsResponse() {}
    
    private readonly global::System.Collections.Generic.List<bnet.protocol.exchange_object_provider.PaymentMethod> _methods = new global::System.Collections.Generic.List<bnet.protocol.exchange_object_provider.PaymentMethod>();
    [global::ProtoBuf.ProtoMember(1, Name=@"methods", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bnet.protocol.exchange_object_provider.PaymentMethod> methods
    {
      get { return _methods; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}