//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: lib/protocol/invitation.proto
// Note: requires additional types generated from: lib/protocol/attribute.proto
// Note: requires additional types generated from: lib/protocol/entity.proto
namespace bnet.protocol.invitation
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Invitation")]
  public partial class Invitation : global::ProtoBuf.IExtensible
  {
    public Invitation() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private bnet.protocol.Identity _inviter_identity;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"inviter_identity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.Identity inviter_identity
    {
      get { return _inviter_identity; }
      set { _inviter_identity = value; }
    }
    private bnet.protocol.Identity _invitee_identity;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"invitee_identity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.Identity invitee_identity
    {
      get { return _invitee_identity; }
      set { _invitee_identity = value; }
    }

    private string _inviter_name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"inviter_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string inviter_name
    {
      get { return _inviter_name; }
      set { _inviter_name = value; }
    }

    private string _invitee_name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"invitee_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string invitee_name
    {
      get { return _invitee_name; }
      set { _invitee_name = value; }
    }

    private string _invitation_message = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"invitation_message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string invitation_message
    {
      get { return _invitation_message; }
      set { _invitation_message = value; }
    }

    private ulong _creation_time = default(ulong);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"creation_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong creation_time
    {
      get { return _creation_time; }
      set { _creation_time = value; }
    }

    private ulong _expiration_time = default(ulong);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"expiration_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong expiration_time
    {
      get { return _expiration_time; }
      set { _expiration_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Suggestion")]
  public partial class Suggestion : global::ProtoBuf.IExtensible
  {
    public Suggestion() {}
    

    private bnet.protocol.EntityId _channel_id = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private bnet.protocol.EntityId _suggester_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"suggester_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId suggester_id
    {
      get { return _suggester_id; }
      set { _suggester_id = value; }
    }
    private bnet.protocol.EntityId _suggestee_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"suggestee_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId suggestee_id
    {
      get { return _suggestee_id; }
      set { _suggestee_id = value; }
    }

    private string _suggester_name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"suggester_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string suggester_name
    {
      get { return _suggester_name; }
      set { _suggester_name = value; }
    }

    private string _suggestee_name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"suggestee_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string suggestee_name
    {
      get { return _suggestee_name; }
      set { _suggestee_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendInvitationRequest")]
  public partial class SendInvitationRequest : global::ProtoBuf.IExtensible
  {
    public SendInvitationRequest() {}
    

    private bnet.protocol.Identity _agent_identity = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"agent_identity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.Identity agent_identity
    {
      get { return _agent_identity; }
      set { _agent_identity = value; }
    }
    private bnet.protocol.EntityId _target_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"target_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bnet.protocol.EntityId target_id
    {
      get { return _target_id; }
      set { _target_id = value; }
    }

    private string _invitation_message = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"invitation_message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string invitation_message
    {
      get { return _invitation_message; }
      set { _invitation_message = value; }
    }

    private ulong _expiration_time = (ulong)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"expiration_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)0)]
    public ulong expiration_time
    {
      get { return _expiration_time; }
      set { _expiration_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendInvitationResponse")]
  public partial class SendInvitationResponse : global::ProtoBuf.IExtensible
  {
    public SendInvitationResponse() {}
    

    private bnet.protocol.invitation.Invitation _invitation = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"invitation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.invitation.Invitation invitation
    {
      get { return _invitation; }
      set { _invitation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GenericRequest")]
  public partial class GenericRequest : global::ProtoBuf.IExtensible
  {
    public GenericRequest() {}
    

    private bnet.protocol.EntityId _agent_id = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"agent_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId agent_id
    {
      get { return _agent_id; }
      set { _agent_id = value; }
    }

    private bnet.protocol.EntityId _target_id = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"target_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bnet.protocol.EntityId target_id
    {
      get { return _target_id; }
      set { _target_id = value; }
    }
    private ulong _invitation_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"invitation_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong invitation_id
    {
      get { return _invitation_id; }
      set { _invitation_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}